/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

import Swing.JtextField.TxtFilter.TxtInteger;
import Swing.JtextField.TxtFilter.TxtIntegerSize;
import Swing.JtextField.TxtFilter.TxtUpper;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import jnafilechooser.api.JnaFileChooser;

/**
 *
 * @author ricar
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        InitIcons();
        loadBackgroundImg();
        IntiFiltersDoc();
    }
    
    public void InitIcons (){
        
        TXT_NOMBRE.setIcon(new FlatSVGIcon("svg/user.svg",25,25));
        searchFolder.setIcon(new FlatSVGIcon("svg/addphoto.svg",35,35) );
        deletePhoto.setIcon(new FlatSVGIcon("svg/deletephoto.svg",35,35) );
        Titulo.setIcon(new FlatSVGIcon("svg/box.svg",35,35));

    }
    public void IntiFiltersDoc(){
        
        TXT_NOMBRE.setDocument(new TxtUpper() {});
        TXT_CANTDAD.setDocument(new TxtIntegerSize(3) {});
        
    }
    
    public void loadBackgroundImg(){
        BackgroundImg.setBackground_Image(new FlatSVGIcon("svg/image.svg",150,150));
    }
    
    public void LoadImg (String Ruta){
        
        
        try {
            // Cargar la imagen desde el archivo
            File archivoImagen = new File(Ruta);
            BufferedImage imagen = ImageIO.read(archivoImagen);
            ImageIcon icono = new ImageIcon(imagen);
            
            BackgroundImg.setBackground_Image(icono);
            
            
            
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new Swing.Panel.JPanel();
        TXT_NOMBRE = new Swing.JtextField.JTextField();
        TXT_CANTDAD = new Swing.JtextField.JTextField();
        BackgroundImg = new Swing.Background.Background_Img();
        searchFolder = new Swing.JButton.JButton();
        deletePhoto = new Swing.JButton.JButton();
        Titulo = new javax.swing.JLabel();

        setOpaque(false);

        TXT_NOMBRE.setPanel_BackgroundGradientColor2(new java.awt.Color(204, 204, 255));
        TXT_NOMBRE.setPanel_BorderActived(true);
        TXT_NOMBRE.setPanel_BorderColor(new java.awt.Color(153, 204, 255));
        TXT_NOMBRE.setPanel_ShadowColor(new java.awt.Color(51, 204, 255));
        TXT_NOMBRE.setTxt_Hint("Nombre del producto");

        TXT_CANTDAD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TXT_CANTDAD.setPanel_BorderActived(true);
        TXT_CANTDAD.setPanel_BorderColor(new java.awt.Color(153, 204, 255));
        TXT_CANTDAD.setPanel_ShadowColor(new java.awt.Color(51, 51, 51));
        TXT_CANTDAD.setTxt_Hint("Cantidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_CANTDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(303, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(TXT_NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_CANTDAD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        BackgroundImg.setBackground_BorderActived(true);
        BackgroundImg.setBackground_BorderColor(new java.awt.Color(230, 230, 230));
        BackgroundImg.setBackground_GradientColor2(new java.awt.Color(204, 153, 0));
        BackgroundImg.setBackground_ImageOpacity(0.0F);
        BackgroundImg.setBackground_Round(3);

        javax.swing.GroupLayout BackgroundImgLayout = new javax.swing.GroupLayout(BackgroundImg);
        BackgroundImg.setLayout(BackgroundImgLayout);
        BackgroundImgLayout.setHorizontalGroup(
            BackgroundImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        BackgroundImgLayout.setVerticalGroup(
            BackgroundImgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        searchFolder.setButton_BorderActived(true);
        searchFolder.setButton_Round(15);
        searchFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFolderActionPerformed(evt);
            }
        });

        deletePhoto.setButton_BorderActived(true);
        deletePhoto.setButton_Round(15);
        deletePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePhotoActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        Titulo.setForeground(new java.awt.Color(102, 102, 102));
        Titulo.setText("  Datos del producto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(BackgroundImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(deletePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackgroundImg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchFolder, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deletePhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(580, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(543, 543, 543))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFolderActionPerformed
        JnaFileChooser jnaCh = new JnaFileChooser();
        //jnaCh.setDefaultFileName("gg.txt");
        boolean save = jnaCh.showSaveDialog(Main.Main.getMain());
        if (save) {
            System.out.println(jnaCh.getSelectedFile());
            LoadImg(String.valueOf(jnaCh.getSelectedFile()));
            
        }
    }//GEN-LAST:event_searchFolderActionPerformed

    private void deletePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePhotoActionPerformed
        BackgroundImg.setBackground_Image(new FlatSVGIcon("svg/image.svg",150,150));
    }//GEN-LAST:event_deletePhotoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.Background.Background_Img BackgroundImg;
    private Swing.JtextField.JTextField TXT_CANTDAD;
    private Swing.JtextField.JTextField TXT_NOMBRE;
    private javax.swing.JLabel Titulo;
    private Swing.JButton.JButton deletePhoto;
    private Swing.Panel.JPanel jPanel1;
    private Swing.JButton.JButton searchFolder;
    // End of variables declaration//GEN-END:variables
}
