/*

 */
package Main;

import Form.Form_Dashboard;
import Form.Form_Empty;
import Form.Form_ProductoRegistrar;
import System.SystemColor;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Menu.EventMenuSelected;
import javax.swing.Icon;
import javax.swing.plaf.metal.MetalIconFactory;
import Util.Glasspanepopup.GlassPanePopup;
import Form.Message.Message;
import Form.Message.Message_Close;

/**
 *
 * @author SOFIA
 */
public class Main2 extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private static Main2 main;
    public Main2() {
        initComponents();
        init();
        setBackground(new Color(0, 0, 0, 0));
        GlassPanePopup.install(this);
        
        BTN_CLOSE.setIconSVG(new FlatSVGIcon("svg/close.svg", 20, 20));
        BTN_MINIMIZE.setIconSVG(new FlatSVGIcon("svg/minimize.svg", 15, 15));
        
        

    }
    private void init() {
        main = this;
        
        
        /*
        MenuBody.addEvent(new EventMenuSelected() {
            @Override
            public void menuSelected(int index, int indexSubMenu) {
                if (index == 0 && indexSubMenu == 0) {
                    showForm(new Form_Dashboard());
                } else if (index == 2 && indexSubMenu == 1) {
                    showForm(new Form_ProductoRegistrar());
                }else{
                    showForm(new Form_Empty(index + " " + indexSubMenu));
                }
            }
        });*/
        MenuBody.setSelectedIndex(0, 0);
    }
    
    public void showForm(Component com) {
        body.removeAll();
        body.add(com);
        body.repaint();
        body.revalidate();
    }
    
    public static Main2 getMain() {
        return main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCustom2 = new Swing.JButtonCustom();
        jPanelCustom2 = new Swing.JPanelCustom();
        BTN_CLOSE = new Swing.JButtonCustom();
        BTN_MINIMIZE = new Swing.JButtonCustom();
        MenuBody = new Menu2.Menu();
        background1 = new Swing.Background();
        body = new javax.swing.JPanel();

        jButtonCustom2.setText("jButtonCustom2");

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_CLOSE.setBackground(new java.awt.Color(255, 61, 61));
        BTN_CLOSE.setColorBorder(new java.awt.Color(255, 102, 102));
        BTN_CLOSE.setIconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_CLOSE.setRound(30);
        BTN_CLOSE.setShadowColor(new java.awt.Color(255, 0, 0));
        BTN_CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 0, 60, 60));

        BTN_MINIMIZE.setColorBorder(new java.awt.Color(230, 230, 230));
        BTN_MINIMIZE.setRound(20);
        BTN_MINIMIZE.setShadowColor(new java.awt.Color(102, 102, 102));
        BTN_MINIMIZE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MINIMIZEActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_MINIMIZE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 0, 50, 50));

        MenuBody.setBackground(new java.awt.Color(153, 0, 255));
        MenuBody.setForeground(new java.awt.Color(102, 102, 255));
        getContentPane().add(MenuBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        background1.setBackground(new java.awt.Color(250, 250, 255));
        background1.setBorderActived(true);
        background1.setColorBorder(new java.awt.Color(102, 0, 204));
        background1.setRound(30);

        body.setBackground(new java.awt.Color(51, 51, 255));
        body.setOpaque(false);
        body.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, 723, Short.MAX_VALUE))
        );

        getContentPane().add(background1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 19, 1420, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    boolean maximized = false;
    private void BTN_CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CLOSEActionPerformed
        Message_Close obj = new Message_Close();
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                System.out.println("Click OK");
                System.exit(0);
                GlassPanePopup.closePopupLast();
            }
        });
        GlassPanePopup.showPopup(obj);
    }//GEN-LAST:event_BTN_CLOSEActionPerformed

    private void BTN_MINIMIZEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MINIMIZEActionPerformed
       this.setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_BTN_MINIMIZEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main2().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.JButtonCustom BTN_CLOSE;
    private Swing.JButtonCustom BTN_MINIMIZE;
    private Menu2.Menu MenuBody;
    private Swing.Background background1;
    private javax.swing.JPanel body;
    private Swing.JButtonCustom jButtonCustom2;
    private Swing.JPanelCustom jPanelCustom2;
    // End of variables declaration//GEN-END:variables
}
