/*

 */
package Main;

import Form.Form_Dashboard;
import Form.Form_Empty;
import Form.Form_ProductoRegistrar;
import System.SystemColor;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import Menu.EventMenuSelected;
import javax.swing.Icon;
import javax.swing.plaf.metal.MetalIconFactory;
import Util.Glasspanepopup.GlassPanePopup;
import Form.Message.Message;
import Form.Message.Message_Close;

/**
 *
 * @author SOFIA
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private static Main main;
    public Main() {
        initComponents();
        init();
        setBackground(new Color(0, 0, 0, 0));
        GlassPanePopup.install(this);
        
        BTN_CLOSE.setIconSVG(new FlatSVGIcon("svg/close.svg", 20, 20));
        BTN_MAXIMIZE.setIconSVG(new FlatSVGIcon("svg/maximize.svg", 15, 15));
        BTN_MINIMIZE.setIconSVG(new FlatSVGIcon("svg/minimize.svg", 15, 15));
        jLabel1.setIcon(new FlatSVGIcon("svg/logo.svg", 45, 45));
        
        

    }
    private void init() {
        main = this;
        MenuBody.addEvent(new EventMenuSelected() {
            @Override
            public void menuSelected(int index, int indexSubMenu) {
                if (index == 0 && indexSubMenu == 0) {
                    showForm(new Form_Dashboard());
                } else if (index == 2 && indexSubMenu == 1) {
                    showForm(new Form_ProductoRegistrar());
                }else{
                    showForm(new Form_Empty(index + " " + indexSubMenu));
                }
            }
        });
        MenuBody.setSelectedIndex(0, 0);
    }
    
    public void showForm(Component com) {
        body.removeAll();
        body.add(com);
        body.repaint();
        body.revalidate();
    }
    
    public static Main getMain() {
        return main;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCustom2 = new Swing.JButtonCustom();
        jPanelCustom2 = new Swing.JPanelCustom();
        background1 = new Swing.Background();
        MenuBody = new Menu.Menu();
        jPanel3 = new javax.swing.JPanel();
        BTN_CLOSE = new Swing.JButtonCustom();
        BTN_MAXIMIZE = new Swing.JButtonCustom();
        jPanelDefault1 = new Swing.JPanelRoundBorder();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelDefault2 = new Swing.JPanelRoundBorder();
        BTN_MINIMIZE = new Swing.JButtonCustom();
        body = new javax.swing.JPanel();

        jButtonCustom2.setText("jButtonCustom2");

        javax.swing.GroupLayout jPanelCustom2Layout = new javax.swing.GroupLayout(jPanelCustom2);
        jPanelCustom2.setLayout(jPanelCustom2Layout);
        jPanelCustom2Layout.setHorizontalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanelCustom2Layout.setVerticalGroup(
            jPanelCustom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        background1.setBackground(new java.awt.Color(23, 24, 30));
        background1.setColorBorder(new java.awt.Color(153, 153, 153));
        background1.setRound(0);

        MenuBody.setBackground(new java.awt.Color(31, 33, 41));
        MenuBody.setForeground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_CLOSE.setBackground(new java.awt.Color(255, 61, 61));
        BTN_CLOSE.setColorBorder(new java.awt.Color(255, 102, 102));
        BTN_CLOSE.setIconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_CLOSE.setShadowColor(new java.awt.Color(255, 61, 61));
        BTN_CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CLOSEActionPerformed(evt);
            }
        });

        BTN_MAXIMIZE.setColorBorder(new java.awt.Color(230, 230, 230));
        BTN_MAXIMIZE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MAXIMIZEActionPerformed(evt);
            }
        });

        jPanelDefault1.setBackground(new java.awt.Color(31, 33, 41));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(245, 249, 250));
        jLabel2.setText("COMPANY S.A.C");

        javax.swing.GroupLayout jPanelDefault1Layout = new javax.swing.GroupLayout(jPanelDefault1);
        jPanelDefault1.setLayout(jPanelDefault1Layout);
        jPanelDefault1Layout.setHorizontalGroup(
            jPanelDefault1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDefault1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelDefault1Layout.setVerticalGroup(
            jPanelDefault1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDefault1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDefault1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanelDefault2.setBackground(new java.awt.Color(31, 33, 41));

        javax.swing.GroupLayout jPanelDefault2Layout = new javax.swing.GroupLayout(jPanelDefault2);
        jPanelDefault2.setLayout(jPanelDefault2Layout);
        jPanelDefault2Layout.setHorizontalGroup(
            jPanelDefault2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDefault2Layout.setVerticalGroup(
            jPanelDefault2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        BTN_MINIMIZE.setColorBorder(new java.awt.Color(230, 230, 230));
        BTN_MINIMIZE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MINIMIZEActionPerformed(evt);
            }
        });

        body.setBackground(new java.awt.Color(51, 51, 255));
        body.setOpaque(false);
        body.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(914, Short.MAX_VALUE))
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MenuBody, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDefault1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelDefault2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(0, 1040, Short.MAX_VALUE)
                        .addComponent(BTN_MINIMIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTN_MAXIMIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(BTN_CLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addComponent(jPanelDefault1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(MenuBody, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanelDefault2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BTN_MAXIMIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_CLOSE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BTN_MINIMIZE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    boolean maximized = false;
    private void BTN_MAXIMIZEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MAXIMIZEActionPerformed

        if (maximized) {
            this.setExtendedState(this.NORMAL);
            BTN_MAXIMIZE.setIconSVG(new FlatSVGIcon("svg/maximize.svg", 15, 15));
                       background1.setRound(30);

        } else {
           this.setExtendedState(this.MAXIMIZED_BOTH);
           BTN_MAXIMIZE.setIconSVG(new FlatSVGIcon("svg/maximize_mini.svg", 15, 15));
           background1.setRound(0);
        }
        maximized = !maximized;

        


    }//GEN-LAST:event_BTN_MAXIMIZEActionPerformed

    private void BTN_CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CLOSEActionPerformed
        Message_Close obj = new Message_Close();
        obj.eventOK(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                System.out.println("Click OK");
                System.exit(0);
                GlassPanePopup.closePopupLast();
            }
        });
        GlassPanePopup.showPopup(obj);
    }//GEN-LAST:event_BTN_CLOSEActionPerformed

    private void BTN_MINIMIZEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MINIMIZEActionPerformed
       this.setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_BTN_MINIMIZEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.JButtonCustom BTN_CLOSE;
    private Swing.JButtonCustom BTN_MAXIMIZE;
    private Swing.JButtonCustom BTN_MINIMIZE;
    private Menu.Menu MenuBody;
    private Swing.Background background1;
    private javax.swing.JPanel body;
    private Swing.JButtonCustom jButtonCustom2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private Swing.JPanelCustom jPanelCustom2;
    private Swing.JPanelRoundBorder jPanelDefault1;
    private Swing.JPanelRoundBorder jPanelDefault2;
    // End of variables declaration//GEN-END:variables
}
