package com.mycompany.LuxcarForm;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ActividadClass;
import com.mycompany.DataBase.Control.ControlActividad;
import com.mycompany.DataBase.Control.ControlMaterial;
import com.mycompany.DataBase.Control.MaterialClass;
import com.mycompany.Popup.PopupConfirMessage;
import com.mycompany.Popup.PopupMessage;
import com.mycompany.Swing.TextField.Filter.TxtUpper;
import com.mycompany.Util.Glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class FormActividad extends javax.swing.JPanel {

    /**
     * Creates new form FormUsuario
     */
    public static ControlActividad DataActividad;

    public FormActividad() {
        initComponents();

        ConectarDataBase();
        ObtenerNuevoIDActividad();
        InicializarTabla();
        MostrarActividad();
        InicializarIcons();
        InicializarTXTDocuments();

    }

    public void ConectarDataBase() {
        DataActividad = new ControlActividad();
    }

    public void InicializarTXTDocuments() {
        DESCRIPCION.setDocument(new TxtUpper() {
        });
    }

    public void ObtenerNuevoIDActividad() {
        ID_MATERIAL.setText(String.valueOf(DataActividad.getIDNuevoActividad()));
    }

    public void LimpiarCampos() {
        DESCRIPCION.setText("");
        ObtenerNuevoIDActividad();
    }

    public boolean ValidarDatos() {
        if (getDescripcion().equals("")) {
            new PopupMessage(
                    "DESCRIPCION DEL MATERIAL",
                    "Debe ingresar una descripcion para el material.",
                    3);
            return false;

        } else {
            return true;
        }

    }

    String getDescripcion() {
        return DESCRIPCION.getText();
    }

    public void InicializarIcons() {
        TXT_BUSQUEDA.setIcon(
                new FlatSVGIcon("svg/buscar.svg", 25, 25));
        BTN_ELIMINAR.setIcon(
                new FlatSVGIcon("svg/user_delete.svg", 25, 25));

    }

    public void InicializarTabla() {

        TABLA_ACTIVIDAD.setHorizontalTextPositionHeader(new int[]{
            SwingConstants.CENTER,
            SwingConstants.LEFT
        });
        TABLA_ACTIVIDAD.setHorizontalTextPosition(new int[]{
            SwingConstants.CENTER,
            SwingConstants.LEFT
        });
        TABLA_ACTIVIDAD.FixScroll(jScrollPane1);

        DataActividad = new ControlActividad((DefaultTableModel) TABLA_ACTIVIDAD.getModel());

    }

    public void MostrarActividad() {
        DataActividad.MostrarTablaActividadBusqueda(TXT_BUSQUEDA.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new com.mycompany.Swing.Panel.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_ACTIVIDAD = new com.mycompany.Swing.Tabla.Tabla();
        TXT_BUSQUEDA = new com.mycompany.Swing.TextField.TextField();
        jPanel1 = new javax.swing.JPanel();
        BTN_ELIMINAR = new com.mycompany.Swing.Button.Button();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new com.mycompany.Swing.Panel.Panel();
        DESCRIPCION = new com.mycompany.Swing.TextField.TextField();
        jLabel1 = new javax.swing.JLabel();
        BTN_REGISTRAR = new com.mycompany.Swing.Button.Button();
        panel3 = new com.mycompany.Swing.Panel.Panel();
        jLabel3 = new javax.swing.JLabel();
        ID_MATERIAL = new javax.swing.JLabel();

        setOpaque(false);

        TABLA_ACTIVIDAD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID Actividad", "Descripcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLA_ACTIVIDAD.setHeader_BackgroundColor(new java.awt.Color(15, 78, 128));
        TABLA_ACTIVIDAD.setHeader_BorderActived(false);
        TABLA_ACTIVIDAD.setHeader_ForegroundColor(new java.awt.Color(255, 255, 255));
        TABLA_ACTIVIDAD.setHeader_Round(7);
        TABLA_ACTIVIDAD.setRow_SelectedColor(new java.awt.Color(204, 204, 204));
        TABLA_ACTIVIDAD.setTable_Border(null);
        TABLA_ACTIVIDAD.setTable_GridLineColor(new java.awt.Color(204, 204, 204));
        TABLA_ACTIVIDAD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TABLA_ACTIVIDADMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA_ACTIVIDAD);
        if (TABLA_ACTIVIDAD.getColumnModel().getColumnCount() > 0) {
            TABLA_ACTIVIDAD.getColumnModel().getColumn(0).setResizable(false);
            TABLA_ACTIVIDAD.getColumnModel().getColumn(0).setPreferredWidth(50);
            TABLA_ACTIVIDAD.getColumnModel().getColumn(1).setResizable(false);
            TABLA_ACTIVIDAD.getColumnModel().getColumn(1).setPreferredWidth(350);
        }

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addContainerGap())
        );

        TXT_BUSQUEDA.setTextField_ShadowSize(3);
        TXT_BUSQUEDA.setTextField_Txthint("Buscar Actividad de servicio");
        TXT_BUSQUEDA.setTextField_TxthintColor(new java.awt.Color(102, 102, 102));
        TXT_BUSQUEDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BUSQUEDAKeyReleased(evt);
            }
        });

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_ELIMINAR.setBackground(new java.awt.Color(255, 61, 61));
        BTN_ELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ELIMINAR.setText("Eliminar");
        BTN_ELIMINAR.setButton_ActivedIconColorFilter(true);
        BTN_ELIMINAR.setButton_BackgroundColorEntered(new java.awt.Color(255, 81, 81));
        BTN_ELIMINAR.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_ELIMINAR.setButton_Round(15);
        BTN_ELIMINAR.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_ELIMINAR.setButton_ShadowSize(3);
        BTN_ELIMINAR.setButton_ShawdowOpacity(0.0F);
        BTN_ELIMINAR.setEnabled(false);
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 141, 48));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 78, 128));
        jLabel2.setText("Busqueda de actividad");

        panel2.setPanel_BackgroundGradientActived(true);
        panel2.setPanel_BackgroundGradientColor1(new java.awt.Color(250, 250, 255));
        panel2.setPanel_BackgroundGradientColor2(new java.awt.Color(250, 255, 255));

        DESCRIPCION.setTextField_BorderActived(true);
        DESCRIPCION.setTextField_BorderColor(new java.awt.Color(153, 153, 153));
        DESCRIPCION.setTextField_Round(0);
        DESCRIPCION.setTextField_ShadowOpacity(0.3F);
        DESCRIPCION.setTextField_ShadowSize(3);
        DESCRIPCION.setTextField_Txthint("Inserte la descripcion de la actividad");
        DESCRIPCION.setTextField_TxthintColor(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Descripcion de la actividad");

        BTN_REGISTRAR.setBackground(new java.awt.Color(15, 71, 128));
        BTN_REGISTRAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_REGISTRAR.setText("Registrar Actividad");
        BTN_REGISTRAR.setButton_ActivedIconColorFilter(true);
        BTN_REGISTRAR.setButton_BackgroundColorEntered(new java.awt.Color(25, 81, 128));
        BTN_REGISTRAR.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_REGISTRAR.setButton_Round(15);
        BTN_REGISTRAR.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_REGISTRAR.setButton_ShadowSize(3);
        BTN_REGISTRAR.setButton_ShawdowOpacity(0.0F);
        BTN_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRARActionPerformed(evt);
            }
        });

        panel3.setPanel_BackgroundGradientActived(true);
        panel3.setPanel_BackgroundGradientColor1(new java.awt.Color(16, 78, 128));
        panel3.setPanel_BackgroundGradientColor2(new java.awt.Color(36, 98, 128));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Registrar Actividad");

        ID_MATERIAL.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ID_MATERIAL.setForeground(new java.awt.Color(255, 255, 255));
        ID_MATERIAL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID_MATERIAL.setText("000");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(ID_MATERIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_MATERIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addContainerGap(50, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                        .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TXT_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_BUSQUEDAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BUSQUEDAKeyReleased
        MostrarActividad();
        BTN_ELIMINAR.setEnabled(false);


    }//GEN-LAST:event_TXT_BUSQUEDAKeyReleased

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        // TODO add your handling code here:
        int filaselected = TABLA_ACTIVIDAD.getSelectedRow();
        if (filaselected > -1) {

            String Id_material = TABLA_ACTIVIDAD.getValueAt(filaselected, 0).toString();

            PopupConfirMessage obj = new PopupConfirMessage(
                    "Eliminar Actividad",
                    "¿Seguro que eliminar esta Actividad?.",
                    new Color(236, 85, 101)
            );

            obj.setTituloForeground(Color.WHITE);
            obj.setIcon_ColorFilter(new Color(236, 85, 101));
            obj.setIcon(new FlatSVGIcon("svg/object.svg", 60, 60), true);
            obj.setCodigo(Id_material);
            obj.setCodigoForeground(Color.WHITE);

            obj.setEventAction(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    DataActividad.EliminarActividad(Integer.parseInt(Id_material));
                    MostrarActividad();
                    ObtenerNuevoIDActividad();
                    BTN_ELIMINAR.setEnabled(false);
                    GlassPanePopup.closePopupLast();
                }
            });
        }


    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void TABLA_ACTIVIDADMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_ACTIVIDADMousePressed
        int filaselected = TABLA_ACTIVIDAD.getSelectedRow();
        if (filaselected > -1) {
            BTN_ELIMINAR.setEnabled(true);
        } else {
            BTN_ELIMINAR.setEnabled(false);
        }
    }//GEN-LAST:event_TABLA_ACTIVIDADMousePressed

    private void BTN_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRARActionPerformed
        // TODO add your handlg coinde here:
        if (ValidarDatos()) {

            ActividadClass NuevoActividad = new ActividadClass();
            NuevoActividad.setID_Actividad(Integer.parseInt(ID_MATERIAL.getText()));
            NuevoActividad.setDescripcion(getDescripcion());
            DataActividad.InsertarActividad(NuevoActividad);
            MostrarActividad();
            
            LimpiarCampos();
            
            new PopupMessage(
                    "¡ ACTIVIDAD REGISTRADO CON EXITO !",
                    "Se ha añadido una nueva actividad a la base de datos..",
                    0
            );
        }

    }//GEN-LAST:event_BTN_REGISTRARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Button.Button BTN_ELIMINAR;
    private com.mycompany.Swing.Button.Button BTN_REGISTRAR;
    private com.mycompany.Swing.TextField.TextField DESCRIPCION;
    private javax.swing.JLabel ID_MATERIAL;
    private com.mycompany.Swing.Tabla.Tabla TABLA_ACTIVIDAD;
    private static com.mycompany.Swing.TextField.TextField TXT_BUSQUEDA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mycompany.Swing.Panel.Panel panel1;
    private com.mycompany.Swing.Panel.Panel panel2;
    private com.mycompany.Swing.Panel.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
