/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.LuxcarForm;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlServicio;
import com.mycompany.DataBase.Control.ControlTrabajador;
import com.mycompany.DataBase.Control.ControlUsuario;
import java.awt.Color;

/**
 *
 * @author ricar
 */
public class FormHome extends javax.swing.JPanel {

    ControlUsuario Usuarios;
    ControlTrabajador Trabajadores;
    ControlServicio DataServicios;

    public FormHome() {
        initComponents();
        InicalizarConexion();
        InicializarCards();
        getCountRowTable();
        

    }
    public void InicalizarConexion(){
        Usuarios = new ControlUsuario();
        Trabajadores = new ControlTrabajador();
        DataServicios = new ControlServicio();
        
    }

    public void InicializarCards() {
        CardUsuarios.setCardActivedFilter();
        CardUsuarios.setCardColorFilter(new Color(255, 255, 255));
        CardUsuarios.setCardIcon(new FlatSVGIcon("svg/user.svg", 70, 70));

        CardTrabajadores.setCardActivedFilter();
        CardTrabajadores.setCardColorFilter(new Color(255, 255, 255));
        CardTrabajadores.setCardIcon(new FlatSVGIcon("svg/worker.svg", 70, 70));

        //cardData3.setCardActivedFilter();
        CardServicios.setCardColorFilter(new Color(255, 255, 255));
        CardServicios.setCardIcon(new FlatSVGIcon("svg/carta.svg", 70, 70));

        //cardData4.setCardActivedFilter();
        CardInformes.setCardColorFilter(new Color(255, 255, 255));
        CardInformes.setCardIcon(new FlatSVGIcon("svg/informe.svg", 70, 70));
    }

    public void getCountRowTable() {
        CardUsuarios.setCardTextNumero(String.valueOf(Usuarios.getTotalUsuarios()));
        CardTrabajadores.setCardTextNumero(String.valueOf(Trabajadores.getTotalTrabajadores()));
        CardServicios.setCardTextNumero(String.valueOf(DataServicios.getTotalServicio()));
        //cardData3.setCardTextNumero(String.valueOf(Usuario.CountRowAllTable("carta")));
        //cardData4.setCardTextNumero(String.valueOf(Usuarios.CountRowAllTable("informe")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CardUsuarios = new com.mycompany.Swing.Card.CardData();
        CardTrabajadores = new com.mycompany.Swing.Card.CardData();
        CardServicios = new com.mycompany.Swing.Card.CardData();
        CardInformes = new com.mycompany.Swing.Card.CardData();

        setOpaque(false);

        CardUsuarios.setCardBackgroundColor(new java.awt.Color(255, 51, 51));
        CardUsuarios.setCardForegroundNumero(java.awt.Color.white);
        CardUsuarios.setCardForegroundTitulo(java.awt.Color.white);
        CardUsuarios.setCardIcon(null);
        CardUsuarios.setCardTextNumero("0");
        CardUsuarios.setCardTextTitulo("Usuarios");

        CardTrabajadores.setCardBackgroundColor(new java.awt.Color(26, 207, 67));
        CardTrabajadores.setCardForegroundNumero(java.awt.Color.white);
        CardTrabajadores.setCardForegroundTitulo(java.awt.Color.white);
        CardTrabajadores.setCardIcon(null);
        CardTrabajadores.setCardTextNumero("0");
        CardTrabajadores.setCardTextTitulo("Trabajadores");

        CardServicios.setCardBackgroundColor(new java.awt.Color(102, 102, 255));
        CardServicios.setCardColorFilter(new java.awt.Color(255, 255, 255));
        CardServicios.setCardForegroundNumero(java.awt.Color.white);
        CardServicios.setCardForegroundTitulo(java.awt.Color.white);
        CardServicios.setCardIcon(null);
        CardServicios.setCardTextNumero("0");
        CardServicios.setCardTextTitulo("Servicios");

        CardInformes.setCardBackgroundColor(new java.awt.Color(102, 102, 102));
        CardInformes.setCardForegroundNumero(java.awt.Color.white);
        CardInformes.setCardForegroundTitulo(java.awt.Color.white);
        CardInformes.setCardIcon(null);
        CardInformes.setCardTextNumero("0");
        CardInformes.setCardTextTitulo("Informes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CardUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CardTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(800, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CardUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CardTrabajadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(CardServicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(CardInformes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(500, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Card.CardData CardInformes;
    private com.mycompany.Swing.Card.CardData CardServicios;
    private com.mycompany.Swing.Card.CardData CardTrabajadores;
    private com.mycompany.Swing.Card.CardData CardUsuarios;
    // End of variables declaration//GEN-END:variables
}
