package com.mycompany.Swing.Card;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlUsuario;
import com.mycompany.Luxcar.Main;
import com.mycompany.LuxcarForm.FormsUsuario.PopupMyUser;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

public class CardUser extends javax.swing.JPanel {

    public CardUser() {
        initComponents();
        ICON.setIcon(
                new FlatSVGIcon("svg/user.svg", 30, 30));

        this.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseReleased(MouseEvent e) {
                if (!Main.getDNIUser().equals("")) {
                    ControlUsuario cu = new ControlUsuario();
                    new PopupMyUser(cu.getUsuario(Main.getDNIUser()));
                    cu.Disconneting();
                } else {
                    new PopupMyUser();
                }

            }

        });

    }

    public void setIconGenero(String genero) {
        switch (genero) {
            case "Masculino":
                ICON.setIcon(
                        new FlatSVGIcon("svg/user_male.svg", 30, 30));
                break;
            case "Femenino":
                ICON.setIcon(
                        new FlatSVGIcon("svg/user_female.svg", 30, 30));
                break;
            default:
                ICON.setIcon(
                        new FlatSVGIcon("svg/user.svg", 30, 30));
        }
    }

    public void setTextNombreUsuario(String nombre) {
        NOMBRE.setText(nombre);
    }

    public void setColorBackground(Color color) {
        BACKGROUND.setBackground(color);
    }

    public void setColorTime(Color color) {
        NOMBRE.setForeground(color);
    }

    public void setIcon(FlatSVGIcon Icon) {
        ICON.setIcon(Icon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new com.mycompany.Swing.Panel.Panel();
        NOMBRE = new javax.swing.JLabel();
        ICON = new com.mycompany.Swing.Label.LabelIcon();

        setOpaque(false);

        NOMBRE.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        NOMBRE.setForeground(new java.awt.Color(102, 102, 102));
        NOMBRE.setText("Usuario");
        NOMBRE.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        ICON.setText(" ");

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BACKGROUNDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Panel.Panel BACKGROUND;
    private com.mycompany.Swing.Label.LabelIcon ICON;
    private javax.swing.JLabel NOMBRE;
    // End of variables declaration//GEN-END:variables

}
