package com.mycompany.Swing.Card;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlServicio;
import com.mycompany.DataBase.DataBase;
import com.mycompany.Luxcar.Main;
import com.mycompany.LuxcarForm.FormServicio;

import java.awt.Color;

import java.util.Timer;
import java.util.TimerTask;

public class CardConnection extends javax.swing.JPanel {

    private DataBase Data;
    private boolean Reconecting = false;

    public CardConnection() {
        initComponents();
        InicializarConexion();
        iniciarContador();
        Connection();

    }

    public void InicializarConexion() {
        Data = new DataBase();
    }

    private void iniciarContador() {
        Connection();
        new Timer(true).scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {

                Connection();

            }
        }, 0, 5 * 1000);

    }

    public void setConnectionUI() {
        STATE.setText("Conectado");
        BACKGROUND.setBackground(new Color(26, 207, 67));
        ICON.setIcon(new FlatSVGIcon("svg/data_conect.svg", 30, 30));
    }

    public void setDisconnectionUI() {
        STATE.setText("Desconectado");
        BACKGROUND.setBackground(new Color(250, 62, 62));
        ICON.setIcon(new FlatSVGIcon("svg/data_discon.svg", 30, 30));
    }

    public void updateMain() {
        int IndexUpdate = Main.ActivedIndex;
        Main.ActivedIndex = -1;
        Main.Menu.setSelectedIndex(IndexUpdate);
        Main.ActivedIndex = IndexUpdate;
    }

    public void Connection() {
        if (!Data.isConnecting() && Reconecting) {
            Data.Reconnect();
            //setConnectionUI();
            updateMain();

        } else if (Data.isConnecting()) {
            ControlServicio cs = new ControlServicio();
            cs.ActualizarEstadosServicio();
            cs.Disconneting();
            //FormServicio.MostrarServicioBusqueda();
            setConnectionUI();
            if (Reconecting) {

                updateMain();

                Reconecting = false;
            }
        } else {
            setDisconnectionUI();
            Reconecting = true;

        }
    }

    public void setColorBackground(Color color) {
        BACKGROUND.setBackground(color);
    }

    public void setColorTime(Color color) {
        STATE.setForeground(color);
    }

    public void setTextTime(String text) {
        STATE.setText(text);
    }

    public void setIcon(FlatSVGIcon Icon) {
        ICON.setIcon(Icon);
    }

    public void setActivedFilter(boolean actived) {
        ICON.setIconColorFilterActived(actived);
    }

    public void setColorFilter(Color color) {
        ICON.setIconColorFilter(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new com.mycompany.Swing.Panel.Panel();
        STATE = new javax.swing.JLabel();
        ICON = new com.mycompany.Swing.Label.LabelIcon();

        setOpaque(false);

        STATE.setBackground(new java.awt.Color(255, 255, 255));
        STATE.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        STATE.setForeground(new java.awt.Color(255, 255, 255));
        STATE.setText("Disconnect");
        STATE.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        ICON.setText(" ");

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(STATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BACKGROUNDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(STATE, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Panel.Panel BACKGROUND;
    private com.mycompany.Swing.Label.LabelIcon ICON;
    private javax.swing.JLabel STATE;
    // End of variables declaration//GEN-END:variables
}
