package com.mycompany.LuxcarForm;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlMaterial;
import com.mycompany.DataBase.Control.ControlTrabajador;
import com.mycompany.DataBase.Control.MaterialClass;
import com.mycompany.DataBase.Control.TrabajadorClass;
import com.mycompany.Popup.PopupConfirMessage;
import com.mycompany.Popup.PopupMessage;
import com.mycompany.Swing.TextField.Filter.TxtDecimalSize;
import com.mycompany.Swing.TextField.Filter.TxtUpper;
import com.mycompany.Util.Glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class FormMaterial extends javax.swing.JPanel {

    /**
     * Creates new form FormUsuario
     */
    public static ControlMaterial DataMaterial;

    public FormMaterial() {
        initComponents();
        DataMaterial = new ControlMaterial();
        ObtenerNuevoMaterial();
        InicializarTabla();
        MostrarMaterial();
        InicializarIcons();
        InicializarTXTDocuments();

    }
    
    public void InicializarTXTDocuments(){
        NOMBRE.setDocument(new TxtUpper(){});
        DESCRIPCION.setDocument(new TxtUpper(){});
        PRECIO_UNITARIO.setDocument(new TxtDecimalSize(2){});
    }

    public void ObtenerNuevoMaterial() {
        ID_MATERIAL.setText(String.valueOf(DataMaterial.getIDNuevoMaterial()));
    }

    public void LimpiarCampos() {
        NOMBRE.setText("");
        DESCRIPCION.setText("");
        UNIDAD.setSelectedIndex(0);
        ObtenerNuevoMaterial();
    }

    public boolean ValidarDatos() {
        String Titulo = "";
        String Mensaje = "";

        if (getNombre().equals("")) {
            Titulo = "NOMBRE DEL MATERIAL";
            Mensaje = "Debe ingresar un nombre para el material.";
            new PopupMessage(Titulo, Mensaje, 3);
            return false;

        } else if (getDescripcion().equals("")) {
            Titulo = "DESCRIPCION DEL MATERIAL";
            Mensaje = "Debe ingresar una descripcion para el material.";
            new PopupMessage(Titulo, Mensaje, 3);
            return false;

        } else if (getUnidad().equals("")) {
            Titulo = "UNIDAD DE MEDIDA";
            Mensaje = "Seleccion una unidad de medida.";
            new PopupMessage(Titulo, Mensaje, 3);
            return false;
        } else if (getPrecioUnitario().equals("")) {
            Titulo = "PRECIO UNITARIO MATERIAL";
            Mensaje = "Debe insertar un precio unitario o inicial del material.";
            new PopupMessage(Titulo, Mensaje, 3);
            return false;
        }else {
            return true;
        }

    }
    String getPrecioUnitario(){
        return PRECIO_UNITARIO.getText();
    }

    String getNombre() {
        return NOMBRE.getText();
    }

    String getDescripcion() {
        return DESCRIPCION.getText();
    }

    String getUnidad() {
        if (UNIDAD.getSelectedIndex() == 0) {
            return "";
        } else {
            return UNIDAD.getSelectedItem().toString();
        }

    }

    public void InicializarIcons() {
        TXT_BUSQUEDA.setIcon(
                new FlatSVGIcon("svg/buscar.svg", 25, 25));
        BTN_ELIMINAR.setIcon(
                new FlatSVGIcon("svg/user_delete.svg", 25, 25));

    }

    public void InicializarTabla() {
        
        TABLA_MATERIAL.setHorizontalTextPositionHeader(new int[]{
            SwingConstants.CENTER,//1 ID Material
            SwingConstants.LEFT,//2 Nombre
            SwingConstants.LEFT,//3 Descripcion
            SwingConstants.CENTER,
            SwingConstants.CENTER//4 Unidad de medida//4 Unidad de medida
        });
        TABLA_MATERIAL.setHorizontalTextPosition(new int[]{
            SwingConstants.CENTER,//1 ID Material
            SwingConstants.LEFT,//2 Nombre
            SwingConstants.LEFT,//3 Descripcion
            SwingConstants.CENTER,
            SwingConstants.RIGHT
        });
        TABLA_MATERIAL.FixScroll(jScrollPane1);
        
        DataMaterial = new ControlMaterial((DefaultTableModel) TABLA_MATERIAL.getModel());

    }

    public void MostrarMaterial() {
        DataMaterial.MostrarTablaMaterialBusqueda(TXT_BUSQUEDA.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new com.mycompany.Swing.Panel.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_MATERIAL = new com.mycompany.Swing.Tabla.Tabla();
        TXT_BUSQUEDA = new com.mycompany.Swing.TextField.TextField();
        jPanel1 = new javax.swing.JPanel();
        BTN_ELIMINAR = new com.mycompany.Swing.Button.Button();
        BTN_MODIFICAR = new com.mycompany.Swing.Button.Button();
        jLabel2 = new javax.swing.JLabel();
        panel2 = new com.mycompany.Swing.Panel.Panel();
        DESCRIPCION = new com.mycompany.Swing.TextField.TextField();
        NOMBRE = new com.mycompany.Swing.TextField.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        UNIDAD = new com.mycompany.Swing.ComboBox.Combobox();
        BTN_REGISTRAR = new com.mycompany.Swing.Button.Button();
        panel3 = new com.mycompany.Swing.Panel.Panel();
        jLabel3 = new javax.swing.JLabel();
        ID_MATERIAL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PRECIO_UNITARIO = new com.mycompany.Swing.TextField.TextField();

        setOpaque(false);

        TABLA_MATERIAL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Material", "Nombre", "Descripcion", "Unidad de medida", "P. Unitario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLA_MATERIAL.setHeader_BackgroundColor(new java.awt.Color(15, 78, 128));
        TABLA_MATERIAL.setHeader_BorderActived(false);
        TABLA_MATERIAL.setHeader_ForegroundColor(new java.awt.Color(255, 255, 255));
        TABLA_MATERIAL.setHeader_Round(7);
        TABLA_MATERIAL.setRow_SelectedColor(new java.awt.Color(204, 204, 204));
        TABLA_MATERIAL.setTable_Border(null);
        TABLA_MATERIAL.setTable_GridLineColor(new java.awt.Color(204, 204, 204));
        TABLA_MATERIAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TABLA_MATERIALMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TABLA_MATERIAL);
        if (TABLA_MATERIAL.getColumnModel().getColumnCount() > 0) {
            TABLA_MATERIAL.getColumnModel().getColumn(0).setResizable(false);
            TABLA_MATERIAL.getColumnModel().getColumn(0).setPreferredWidth(50);
            TABLA_MATERIAL.getColumnModel().getColumn(1).setResizable(false);
            TABLA_MATERIAL.getColumnModel().getColumn(1).setPreferredWidth(150);
            TABLA_MATERIAL.getColumnModel().getColumn(2).setResizable(false);
            TABLA_MATERIAL.getColumnModel().getColumn(2).setPreferredWidth(200);
            TABLA_MATERIAL.getColumnModel().getColumn(3).setPreferredWidth(70);
            TABLA_MATERIAL.getColumnModel().getColumn(4).setResizable(false);
            TABLA_MATERIAL.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                .addContainerGap())
        );

        TXT_BUSQUEDA.setTextField_ShadowSize(3);
        TXT_BUSQUEDA.setTextField_Txthint("Buscar material.");
        TXT_BUSQUEDA.setTextField_TxthintColor(new java.awt.Color(102, 102, 102));
        TXT_BUSQUEDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TXT_BUSQUEDAKeyReleased(evt);
            }
        });

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN_ELIMINAR.setBackground(new java.awt.Color(255, 61, 61));
        BTN_ELIMINAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ELIMINAR.setText("Eliminar");
        BTN_ELIMINAR.setButton_ActivedIconColorFilter(true);
        BTN_ELIMINAR.setButton_BackgroundColorEntered(new java.awt.Color(255, 81, 81));
        BTN_ELIMINAR.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_ELIMINAR.setButton_Round(15);
        BTN_ELIMINAR.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_ELIMINAR.setButton_ShadowSize(3);
        BTN_ELIMINAR.setButton_ShawdowOpacity(0.0F);
        BTN_ELIMINAR.setEnabled(false);
        BTN_ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ELIMINARActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 141, 48));

        BTN_MODIFICAR.setBackground(new java.awt.Color(255, 61, 61));
        BTN_MODIFICAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_MODIFICAR.setText("Modificar");
        BTN_MODIFICAR.setButton_ActivedIconColorFilter(true);
        BTN_MODIFICAR.setButton_BackgroundColorEntered(new java.awt.Color(255, 81, 81));
        BTN_MODIFICAR.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_MODIFICAR.setButton_Round(15);
        BTN_MODIFICAR.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_MODIFICAR.setButton_ShadowSize(3);
        BTN_MODIFICAR.setButton_ShawdowOpacity(0.0F);
        BTN_MODIFICAR.setEnabled(false);
        BTN_MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_MODIFICARActionPerformed(evt);
            }
        });
        jPanel1.add(BTN_MODIFICAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 48));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 78, 128));
        jLabel2.setText("BUSCAR MATERIAL");

        panel2.setPanel_BackgroundGradientActived(true);
        panel2.setPanel_BackgroundGradientColor1(new java.awt.Color(250, 250, 255));
        panel2.setPanel_BackgroundGradientColor2(new java.awt.Color(250, 255, 255));

        DESCRIPCION.setTextField_BorderActived(true);
        DESCRIPCION.setTextField_BorderColor(new java.awt.Color(153, 153, 153));
        DESCRIPCION.setTextField_Round(0);
        DESCRIPCION.setTextField_ShadowOpacity(0.3F);
        DESCRIPCION.setTextField_ShadowSize(3);
        DESCRIPCION.setTextField_Txthint("Ingrese Descripcion del Material");
        DESCRIPCION.setTextField_TxthintColor(new java.awt.Color(153, 153, 153));

        NOMBRE.setTextField_BorderActived(true);
        NOMBRE.setTextField_BorderColor(new java.awt.Color(153, 153, 153));
        NOMBRE.setTextField_Round(0);
        NOMBRE.setTextField_ShadowOpacity(0.3F);
        NOMBRE.setTextField_ShadowSize(3);
        NOMBRE.setTextField_Txthint("Ingrese Nombre del Material");
        NOMBRE.setTextField_TxthintColor(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Nombre del material");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Descripcion del material");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Unidad de medida");

        UNIDAD.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione una unidad de medida.", "Centímetros (cm)", "Metros (m)", "Pulgadas (in)", "Gramos (g)", "Kilogramos (kg)", "Mililitros (ml)", "Litros (l)", "Centímetros cuadrados (cm²)", "Metros cuadrados (m²)" }));

        BTN_REGISTRAR.setBackground(new java.awt.Color(15, 71, 128));
        BTN_REGISTRAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_REGISTRAR.setText("Registrar material");
        BTN_REGISTRAR.setButton_ActivedIconColorFilter(true);
        BTN_REGISTRAR.setButton_BackgroundColorEntered(new java.awt.Color(25, 81, 128));
        BTN_REGISTRAR.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_REGISTRAR.setButton_Round(15);
        BTN_REGISTRAR.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_REGISTRAR.setButton_ShadowSize(3);
        BTN_REGISTRAR.setButton_ShawdowOpacity(0.0F);
        BTN_REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGISTRARActionPerformed(evt);
            }
        });

        panel3.setPanel_BackgroundGradientActived(true);
        panel3.setPanel_BackgroundGradientColor1(new java.awt.Color(16, 78, 128));
        panel3.setPanel_BackgroundGradientColor2(new java.awt.Color(36, 98, 128));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 19)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRAR MATERIAL");

        ID_MATERIAL.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ID_MATERIAL.setForeground(new java.awt.Color(255, 255, 255));
        ID_MATERIAL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID_MATERIAL.setText("000");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addGap(108, 108, 108)
                .addComponent(ID_MATERIAL, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_MATERIAL, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Precio Unitario");

        PRECIO_UNITARIO.setTextField_BorderActived(true);
        PRECIO_UNITARIO.setTextField_BorderColor(new java.awt.Color(153, 153, 153));
        PRECIO_UNITARIO.setTextField_Round(0);
        PRECIO_UNITARIO.setTextField_ShadowOpacity(0.3F);
        PRECIO_UNITARIO.setTextField_ShadowSize(3);
        PRECIO_UNITARIO.setTextField_Txthint("0.00");
        PRECIO_UNITARIO.setTextField_TxthintColor(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PRECIO_UNITARIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(NOMBRE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DESCRIPCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(UNIDAD, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))))
                .addGap(50, 50, 50))
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NOMBRE, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UNIDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PRECIO_UNITARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(BTN_REGISTRAR, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXT_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TXT_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_BUSQUEDAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_BUSQUEDAKeyReleased
        MostrarMaterial();
        BTN_ELIMINAR.setEnabled(false);


    }//GEN-LAST:event_TXT_BUSQUEDAKeyReleased

    private void BTN_ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ELIMINARActionPerformed
        // TODO add your handling code here:
        int filaselected = TABLA_MATERIAL.getSelectedRow();
        if (filaselected > -1) {

            String Id_material = TABLA_MATERIAL.getValueAt(filaselected, 0).toString();

            PopupConfirMessage obj = new PopupConfirMessage(
                    "Eliminar Material", 
                    "¿Seguro que eliminar a este trabajador?.", 
                    new Color(236, 85, 101)
            );

            obj.setTituloForeground(Color.WHITE);
            obj.setIcon_ColorFilter(new Color(236, 85, 101));
            obj.setIcon(new FlatSVGIcon("svg/object.svg", 60, 60),true);
            obj.setCodigo(Id_material);
            obj.setCodigoForeground(Color.WHITE);

            obj.setEventAction(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    DataMaterial.EliminarMaterial(Integer.parseInt(Id_material));
                    MostrarMaterial();
                    ObtenerNuevoMaterial();
                    BTN_ELIMINAR.setEnabled(false);
                    GlassPanePopup.closePopupLast();
                }
            });
        }


    }//GEN-LAST:event_BTN_ELIMINARActionPerformed

    private void TABLA_MATERIALMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLA_MATERIALMousePressed
        // TODO add your handling code here:
        int filaselected = TABLA_MATERIAL.getSelectedRow();
        if (filaselected > -1) {
            BTN_ELIMINAR.setEnabled(true);
        } else {
            BTN_ELIMINAR.setEnabled(false);
        }
    }//GEN-LAST:event_TABLA_MATERIALMousePressed

    private void BTN_REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGISTRARActionPerformed
        // TODO add your handlg coinde here:
        if(ValidarDatos()){
            
            MaterialClass NuevoMaterial = new MaterialClass();
            NuevoMaterial.setID_Material(Integer.parseInt(ID_MATERIAL.getText()));
            NuevoMaterial.setNombre(getNombre());
            NuevoMaterial.setDescripcion(getDescripcion());
            NuevoMaterial.setUnidadMedida(getUnidad());
            NuevoMaterial.setPrecioUnitario(Double.parseDouble(getPrecioUnitario()));
            DataMaterial.InsertarMaterial(NuevoMaterial);
            MostrarMaterial();
            LimpiarCampos();
            new PopupMessage(
                    "¡ MATERIAL REGISTRADO CON EXITO !",
                    "Se ha añadido un nuevo material al inventario de la empresa.",
                    0
            );
        }

    }//GEN-LAST:event_BTN_REGISTRARActionPerformed

    private void BTN_MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_MODIFICARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_MODIFICARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Button.Button BTN_ELIMINAR;
    private com.mycompany.Swing.Button.Button BTN_MODIFICAR;
    private com.mycompany.Swing.Button.Button BTN_REGISTRAR;
    private com.mycompany.Swing.TextField.TextField DESCRIPCION;
    private javax.swing.JLabel ID_MATERIAL;
    private com.mycompany.Swing.TextField.TextField NOMBRE;
    private com.mycompany.Swing.TextField.TextField PRECIO_UNITARIO;
    private com.mycompany.Swing.Tabla.Tabla TABLA_MATERIAL;
    private static com.mycompany.Swing.TextField.TextField TXT_BUSQUEDA;
    private com.mycompany.Swing.ComboBox.Combobox UNIDAD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mycompany.Swing.Panel.Panel panel1;
    private com.mycompany.Swing.Panel.Panel panel2;
    private com.mycompany.Swing.Panel.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
