package com.mycompany.LuxcarForm.FormsServicio;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlServicio;
import com.mycompany.DataBase.Control.ServicioClass;
import com.mycompany.DataBase.Control.TrabajadorClass;
import com.mycompany.Luxcar.Utilidades;
import com.mycompany.LuxcarForm.FormServicio;
import com.mycompany.Popup.PopupMessage;
import com.mycompany.Util.Glasspanepopup.DefaultOption;
import com.mycompany.Util.Glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalDateTime;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class FormModificarServicio extends javax.swing.JPanel {

    public ControlServicio DataServicio;

    public FormModificarServicio() {
        initComponents();
        DataServicio = new ControlServicio();
        InicializarIcons();

        GlassPanePopup.showPopup(this, new DefaultOption() {
            @Override
            public Color background() {
                return new Color(0, 0, 0);
            }

            @Override
            public int duration() {
                return 100;
            }

        });

    }

    public void InicializarIcons() {
        TITTLE.setIcon(new FlatSVGIcon("svg/service.svg", 60, 60));
    }

    public FormModificarServicio(ServicioClass Servicio) {
        this();

        ID_SERVICIO.setText(String.valueOf(Servicio.getIDServicio()));
        UBICACION.setText(Servicio.getUbicacion());
        DESCRIPCION.setText(Servicio.getDescripcion());
        LocalDateTime datetime = Servicio.getFechaInicio();
        DIA.setValue(datetime.getDayOfMonth());
        MES.setValue(Utilidades.getMesEnEspanol(datetime.getMonth()));
        AÑO.setValue(datetime.getYear());
        HORA.setValue(datetime.getHour());
        MINUTO.setValue(datetime.getMinute());
        ESTADO.setText(Servicio.getEstado());
        VerificarHoraAttemps();
    }

    String getUbicacion() {
        return UBICACION.getText();
    }

    String getDescripcion() {
        return DESCRIPCION.getText();
    }

    int getIdServicio() {
        return Integer.parseInt(ID_SERVICIO.getText());
    }

    public String getEstadoDelServicio() {
        LocalDateTime fechaActual = LocalDateTime.now();

        if (getFechaDeEjecucion().isAfter(fechaActual)) {
            return "Sin Comenzar";
        } else {
            return "En proceso";
        }
    }

    public void compararFechas() {
        LocalDateTime fechaActual = LocalDateTime.now();
        if (getFechaDeEjecucion() != null) {
            if (getFechaDeEjecucion().isAfter(fechaActual)) {
                ESTADO.setText("Sin Comenzar");
            } else {
                ESTADO.setText("En proceso");
            }
        }

    }

    LocalDateTime getFechaDeEjecucion() {
        LocalDate date = Utilidades.getFechaSpinnerx3_dd_StringMes_yyyy(
                DIA.getValue().toString(),
                MES.getValue().toString(),
                AÑO.getValue().toString());

        return Utilidades.getDateTime(
                date,
                HORA.getValue().toString(),
                MINUTO.getValue().toString()
        );
    }

    public void ObtenerNuevoIDServicio() {
        ID_SERVICIO.setText(String.valueOf(DataServicio.getIDNuevoServicio()));
    }

    public boolean ValidarDatos() {
        if (getUbicacion().equals("")) {
            new PopupMessage("UBICACION", "El campo Ubicacion esta vacio.", 3);
            return false;

        } else if (getDescripcion().equals("")) {
            new PopupMessage("DESCRIPCION", "El campo descripcion esta vacio.", 3);
            return false;

        } else if (getFechaDeEjecucion() == null) {
            new PopupMessage("FECHA", "La fecha es invalido.", 3);
            return false;
        } else {
            return true;
        }

    }

    void VerificarHoraAttemps() {
        if (Integer.parseInt(HORA.getValue().toString()) >= 12) {
            ampm.setText("P.M.");
        } else {
            ampm.setText("A.M.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panel2 = new com.mycompany.Swing.Panel.Panel();
        DESCRIPCION = new com.mycompany.Swing.TextField.TextField();
        panel4 = new com.mycompany.Swing.Panel.Panel();
        HORA = new com.mycompany.Swing.Spinner.SpinnerHora();
        MINUTO = new com.mycompany.Swing.Spinner.SpinnerMinuto();
        ampm = new javax.swing.JLabel();
        ampm1 = new javax.swing.JLabel();
        panel6 = new com.mycompany.Swing.Panel.Panel();
        DIA = new com.mycompany.Swing.Spinner.SpinnerDia();
        MES = new com.mycompany.Swing.Spinner.SpinnerMes();
        AÑO = new com.mycompany.Swing.Spinner.SpinnerAño();
        UBICACION = new com.mycompany.Swing.TextField.TextField();
        BTN_ACTION = new com.mycompany.Swing.Button.Button();
        BTN_ACTION1 = new com.mycompany.Swing.Button.Button();
        BACKGROUND = new com.mycompany.Swing.Panel.Panel();
        TITTLE = new com.mycompany.Swing.Label.LabelIcon();
        ID_SERVICIO = new javax.swing.JLabel();
        TITTLE2 = new com.mycompany.Swing.Label.LabelIcon();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new com.mycompany.Swing.Panel.Panel();
        ESTADO = new javax.swing.JLabel();

        setOpaque(false);

        panel2.setPanel_BackgroundGradientActived(true);
        panel2.setPanel_BackgroundGradientColor2(new java.awt.Color(250, 250, 250));
        panel2.setPanel_ShadowOpacity(0.3F);
        panel2.setPanel_ShadowSize(3);
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel2MouseEntered(evt);
            }
        });

        DESCRIPCION.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        DESCRIPCION.setTextField_ActivedIconColorFilter(true);
        DESCRIPCION.setTextField_BorderActived(true);
        DESCRIPCION.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        DESCRIPCION.setTextField_IconColorFilter(new java.awt.Color(0, 0, 0));
        DESCRIPCION.setTextField_Round(5);
        DESCRIPCION.setTextField_ShadowColor(new java.awt.Color(16, 78, 128));
        DESCRIPCION.setTextField_ShadowOpacity(0.3F);
        DESCRIPCION.setTextField_ShadowSize(3);
        DESCRIPCION.setTextField_Txthint("Descripcion del servicio");
        DESCRIPCION.setTextField_TxthintColor(new java.awt.Color(183, 193, 173));

        panel4.setPanel_BorderActived(true);
        panel4.setPanel_BorderColor(new java.awt.Color(204, 204, 204));
        panel4.setPanel_Round(7);
        panel4.setPanel_ShadowOpacity(0.3F);
        panel4.setPanel_ShadowSize(3);
        panel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel4MouseExited(evt);
            }
        });
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HORA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HORAMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HORAMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HORAMousePressed(evt);
            }
        });
        HORA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HORAKeyReleased(evt);
            }
        });
        panel4.add(HORA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 80, 50));
        panel4.add(MINUTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 80, 50));

        ampm.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        ampm.setText("A.M.");
        panel4.add(ampm, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 50, 50));

        ampm1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        ampm1.setText(":");
        panel4.add(ampm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 10, 50));

        panel6.setPanel_BorderActived(true);
        panel6.setPanel_BorderColor(new java.awt.Color(204, 204, 204));
        panel6.setPanel_Round(7);
        panel6.setPanel_ShadowOpacity(0.3F);
        panel6.setPanel_ShadowSize(3);
        panel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel6MouseExited(evt);
            }
        });
        panel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DIA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                DIAMouseReleased(evt);
            }
        });
        panel6.add(DIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 50));
        panel6.add(MES, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 150, 50));
        panel6.add(AÑO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 50));

        UBICACION.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        UBICACION.setTextField_ActivedIconColorFilter(true);
        UBICACION.setTextField_BorderActived(true);
        UBICACION.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        UBICACION.setTextField_IconColorFilter(new java.awt.Color(0, 0, 0));
        UBICACION.setTextField_Round(5);
        UBICACION.setTextField_ShadowColor(new java.awt.Color(16, 78, 128));
        UBICACION.setTextField_ShadowOpacity(0.3F);
        UBICACION.setTextField_ShadowSize(3);
        UBICACION.setTextField_Txthint("Ubicacion o lugar del servicio");
        UBICACION.setTextField_TxthintColor(new java.awt.Color(183, 193, 173));
        UBICACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UBICACIONActionPerformed(evt);
            }
        });

        BTN_ACTION.setBackground(new java.awt.Color(51, 51, 51));
        BTN_ACTION.setForeground(new java.awt.Color(255, 255, 255));
        BTN_ACTION.setText("GUARDAR");
        BTN_ACTION.setButton_ActivedIconColorFilter(true);
        BTN_ACTION.setButton_BackgroundColorEntered(new java.awt.Color(102, 102, 102));
        BTN_ACTION.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_ACTION.setButton_Round(15);
        BTN_ACTION.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_ACTION.setButton_ShadowSize(3);
        BTN_ACTION.setButton_ShawdowOpacity(0.0F);
        BTN_ACTION.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        BTN_ACTION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACTIONActionPerformed(evt);
            }
        });

        BTN_ACTION1.setForeground(new java.awt.Color(51, 51, 51));
        BTN_ACTION1.setText("CANCELAR");
        BTN_ACTION1.setButton_ActivedIconColorFilter(true);
        BTN_ACTION1.setButton_BackgroundColorEntered(new java.awt.Color(204, 204, 204));
        BTN_ACTION1.setButton_IconColorFilter(new java.awt.Color(255, 255, 255));
        BTN_ACTION1.setButton_Round(15);
        BTN_ACTION1.setButton_ShadowColor(new java.awt.Color(15, 71, 128));
        BTN_ACTION1.setButton_ShadowSize(3);
        BTN_ACTION1.setButton_ShawdowOpacity(0.4F);
        BTN_ACTION1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        BTN_ACTION1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACTION1ActionPerformed(evt);
            }
        });

        BACKGROUND.setBackground(new java.awt.Color(16, 78, 128));
        BACKGROUND.setPanel_BackgroundGradientActived(true);
        BACKGROUND.setPanel_BackgroundGradientColor1(new java.awt.Color(51, 51, 51));
        BACKGROUND.setPanel_BackgroundGradientColor2(new java.awt.Color(51, 51, 51));
        BACKGROUND.setPanel_Round(10);
        BACKGROUND.setPanel_ShadowOpacity(0.3F);
        BACKGROUND.setPanel_ShadowSize(3);

        TITTLE.setForeground(new java.awt.Color(255, 255, 255));
        TITTLE.setText("Modificar servicio");
        TITTLE.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        TITTLE.setIconColorFilterActived(true);

        ID_SERVICIO.setBackground(new java.awt.Color(16, 78, 128));
        ID_SERVICIO.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        ID_SERVICIO.setForeground(new java.awt.Color(255, 255, 255));
        ID_SERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ID_SERVICIO.setText("000");
        ID_SERVICIO.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(TITTLE, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addComponent(ID_SERVICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TITTLE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ID_SERVICIO, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        TITTLE2.setForeground(new java.awt.Color(51, 51, 51));
        TITTLE2.setText("Datos del servicio");
        TITTLE2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TITTLE2.setIconColorFilter(new java.awt.Color(16, 71, 128));
        TITTLE2.setIconColorFilterActived(true);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("  Fecha y hora de ejecucion.");

        panel1.setBackground(new java.awt.Color(120, 120, 120));

        ESTADO.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        ESTADO.setForeground(new java.awt.Color(255, 255, 255));
        ESTADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ESTADO.setText("Estado del servicio");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ESTADO, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(ESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addComponent(BTN_ACTION1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_ACTION, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(DESCRIPCION, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                            .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel2Layout.createSequentialGroup()
                            .addComponent(TITTLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(UBICACION, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
            .addComponent(BACKGROUND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TITTLE2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(UBICACION, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(DESCRIPCION, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_ACTION, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_ACTION1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void HORAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HORAMouseEntered
        VerificarHoraAttemps();
    }//GEN-LAST:event_HORAMouseEntered

    private void HORAMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HORAMouseExited
        VerificarHoraAttemps();
    }//GEN-LAST:event_HORAMouseExited

    private void HORAMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HORAMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_HORAMousePressed

    private void HORAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HORAKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_HORAKeyReleased

    private void panel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MouseEntered
        VerificarHoraAttemps();
        compararFechas();
    }//GEN-LAST:event_panel4MouseEntered

    private void panel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel4MouseExited
        VerificarHoraAttemps();
        compararFechas();
    }//GEN-LAST:event_panel4MouseExited

    private void BTN_ACTIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACTIONActionPerformed
        if (ValidarDatos()) {
            ServicioClass ModificarServicio = new ServicioClass();
            ModificarServicio.setIDServicio(getIdServicio());//1
            ModificarServicio.setUbicacion(getUbicacion());//2
            ModificarServicio.setDescripcion(getDescripcion());//3
            ModificarServicio.setFechaInicio(getFechaDeEjecucion());//4
            ModificarServicio.setEstado(getEstadoDelServicio());//5
            ModificarServicio.setFechaServicoRegistrado(LocalDateTime.now());//6

            DataServicio.ModificarServicio(ModificarServicio);
            FormServicio.MostrarServicioBusqueda();
            DataServicio.Disconneting();

            GlassPanePopup.closePopupLast();
            new PopupMessage(
                    "¡ SERVICIO MODIFICADO CON EXITO !",
                    "Se ha añadido un nuevo servicio .",
                    0
            );

        }

    }//GEN-LAST:event_BTN_ACTIONActionPerformed

    private void panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseEntered
        VerificarHoraAttemps();
        compararFechas();
    }//GEN-LAST:event_panel2MouseEntered

    private void UBICACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UBICACIONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UBICACIONActionPerformed

    private void BTN_ACTION1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACTION1ActionPerformed
        BTN_ACTION1.setEnabled(false);
        GlassPanePopup.closePopupLast();
        DataServicio.Disconneting();
    }//GEN-LAST:event_BTN_ACTION1ActionPerformed

    private void DIAMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIAMouseReleased
        // TODO add your handling code here:
        compararFechas();
    }//GEN-LAST:event_DIAMouseReleased

    private void panel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel6MouseEntered
        compararFechas();
    }//GEN-LAST:event_panel6MouseEntered

    private void panel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel6MouseExited
        compararFechas();
    }//GEN-LAST:event_panel6MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Spinner.SpinnerAño AÑO;
    private com.mycompany.Swing.Panel.Panel BACKGROUND;
    private com.mycompany.Swing.Button.Button BTN_ACTION;
    private com.mycompany.Swing.Button.Button BTN_ACTION1;
    private com.mycompany.Swing.TextField.TextField DESCRIPCION;
    private com.mycompany.Swing.Spinner.SpinnerDia DIA;
    private javax.swing.JLabel ESTADO;
    private com.mycompany.Swing.Spinner.SpinnerHora HORA;
    private javax.swing.JLabel ID_SERVICIO;
    private com.mycompany.Swing.Spinner.SpinnerMes MES;
    private com.mycompany.Swing.Spinner.SpinnerMinuto MINUTO;
    private com.mycompany.Swing.Label.LabelIcon TITTLE;
    private com.mycompany.Swing.Label.LabelIcon TITTLE2;
    private com.mycompany.Swing.TextField.TextField UBICACION;
    public static javax.swing.JLabel ampm;
    public static javax.swing.JLabel ampm1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private com.mycompany.Swing.Panel.Panel panel1;
    private com.mycompany.Swing.Panel.Panel panel2;
    private com.mycompany.Swing.Panel.Panel panel4;
    private com.mycompany.Swing.Panel.Panel panel6;
    // End of variables declaration//GEN-END:variables
}
