package com.mycompany.Swing.Card;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;

public class CardData extends javax.swing.JPanel {

    public CardData() {
        initComponents();

    }

    public void setCardTextNumero(String text) {
        NUMERO.setText(text);
    }

    public void setCardTextTitulo(String text) {
        TITULO.setText(text);
    }

    public void setCardForegroundNumero(Color color) {
        NUMERO.setForeground(color);
    }

    public void setCardForegroundTitulo(Color color) {
        TITULO.setForeground(color);
    }

    public void setCardIcon(FlatSVGIcon Icon) {
        ICON.setIcon(Icon);
    }

    public void setCardActivedFilter() {
        ICON.setIconColorFilterActived(true);
    }

    public void setCardColorFilter(Color color) {
        ICON.setIconColorFilter(color);
    }

    public void setCardBackgroundColor(Color color) {
        BACKGROUND.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new com.mycompany.Swing.Panel.Panel();
        TITULO = new javax.swing.JLabel();
        NUMERO = new javax.swing.JLabel();
        ICON = new com.mycompany.Swing.Label.LabelIcon();

        setOpaque(false);

        BACKGROUND.setPanel_ShadowColor(getBackground());

        TITULO.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        TITULO.setText("Titulo");

        NUMERO.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        NUMERO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUMERO.setText("000");
        NUMERO.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TITULO, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(NUMERO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BACKGROUNDLayout.createSequentialGroup()
                        .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(NUMERO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Panel.Panel BACKGROUND;
    private com.mycompany.Swing.Label.LabelIcon ICON;
    private javax.swing.JLabel NUMERO;
    private javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
