package com.mycompany.Swing.Card;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.Color;
import java.awt.event.ActionListener;

public class CardDataAction extends javax.swing.JPanel {

    public CardDataAction() {
        initComponents();

    }

    public void setActionEvent(ActionListener evt) {
        BTN.addActionListener(evt);

    }
    public void setvisibleBTN (boolean actived){
        BTN.setVisible(actived);
    }

    public void setCardTextNumero(String text) {
        NUMERO.setText(text);
    }

    public void setCardTextTitulo(String text) {
        TITULO.setText(text);
    }

    public void setCardForegroundNumero(Color color) {
        NUMERO.setForeground(color);
    }

    public void setCardForegroundTitulo(Color color) {
        TITULO.setForeground(color);
    }

    public void setCardIcon(FlatSVGIcon Icon) {
        ICON.setIcon(Icon);
    }

    public void setCardActivedFilter() {
        ICON.setIconColorFilterActived(true);
    }

    public void setCardColorFilter(Color color) {
        ICON.setIconColorFilter(color);
    }

    public void setCardBackgroundColor(Color color) {
        BACKGROUND.setBackground(color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new com.mycompany.Swing.Panel.Panel();
        TITULO = new javax.swing.JLabel();
        NUMERO = new javax.swing.JLabel();
        ICON = new com.mycompany.Swing.Label.LabelIcon();
        BTN = new com.mycompany.Swing.Button.Button();

        setOpaque(false);

        BACKGROUND.setPanel_Round(7);
        BACKGROUND.setPanel_ShadowColor(getBackground());
        BACKGROUND.setPanel_ShadowSize(3);

        TITULO.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        TITULO.setText("Titulo");

        NUMERO.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        NUMERO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUMERO.setText("000");
        NUMERO.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        ICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        BTN.setForeground(new java.awt.Color(51, 51, 51));
        BTN.setText("Ver");
        BTN.setButton_BackgroundColorEntered(new java.awt.Color(230, 230, 255));
        BTN.setButton_Round(7);
        BTN.setButton_ShadowSize(3);
        BTN.setButton_ShawdowOpacity(0.3F);
        BTN.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NUMERO, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(TITULO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BTN, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BACKGROUNDLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BACKGROUNDLayout.createSequentialGroup()
                        .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(BACKGROUNDLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(TITULO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NUMERO, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Panel.Panel BACKGROUND;
    private com.mycompany.Swing.Button.Button BTN;
    private com.mycompany.Swing.Label.LabelIcon ICON;
    private javax.swing.JLabel NUMERO;
    private javax.swing.JLabel TITULO;
    // End of variables declaration//GEN-END:variables
}
