package com.mycompany.Swing.Card;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter;
import com.mycompany.Util.Shadow.ShadowRenderer;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.time.LocalDateTime;
import javax.swing.Icon;
import java.time.format.DateTimeFormatter;
import java.util.Timer;
import java.util.TimerTask;

public class CardTime extends javax.swing.JPanel {

    DateTimeFormatter formatoFechayHora;

    public CardTime() {
        initComponents();
        ICON.setIcon(
                new FlatSVGIcon("svg/time.svg", 30, 30));
        formatoFechayHora = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        new Timer(true).scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                actualizarHora();
            }
        }, 0, 1000);

    }

    private void actualizarHora() {
        // Obtener la fecha y hora actual
        LocalDateTime ahora = LocalDateTime.now();
        String fechaHoraFormateada = ahora.format(formatoFechayHora);

        // Actualizar la etiqueta
        TIME.setText(fechaHoraFormateada);
    }
    public String getFecha(){
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime ahora = LocalDateTime.now();
        return ahora.format(formatoFecha);
    }
    public String getHora(){
        DateTimeFormatter formatoFecha = DateTimeFormatter.ofPattern("HH:mm:ss");
        LocalDateTime ahora = LocalDateTime.now();
        return ahora.format(formatoFecha);
    }
    public void setColorBackground(Color color){
        BACKGROUND.setBackground(color);
    }
    public void setColorTime(Color color){
        TIME.setForeground(color);
    }

    public void setTextTime(String text) {
        TIME.setText(text);
    }

    public void setIcon(FlatSVGIcon Icon) {
        ICON.setIcon(Icon);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BACKGROUND = new com.mycompany.Swing.Panel.Panel();
        TIME = new javax.swing.JLabel();
        ICON = new com.mycompany.Swing.Label.LabelIcon();

        setOpaque(false);

        TIME.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        TIME.setForeground(new java.awt.Color(102, 102, 102));
        TIME.setText("hh:mm:ss");
        TIME.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        ICON.setText(" ");

        javax.swing.GroupLayout BACKGROUNDLayout = new javax.swing.GroupLayout(BACKGROUND);
        BACKGROUND.setLayout(BACKGROUNDLayout);
        BACKGROUNDLayout.setHorizontalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BACKGROUNDLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(ICON, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TIME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        BACKGROUNDLayout.setVerticalGroup(
            BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BACKGROUNDLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(BACKGROUNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TIME, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(BACKGROUND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Panel.Panel BACKGROUND;
    private com.mycompany.Swing.Label.LabelIcon ICON;
    private javax.swing.JLabel TIME;
    // End of variables declaration//GEN-END:variables
}
