/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.LuxcarForm.FormsTrabajador;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlServicio;
import com.mycompany.DataBase.Control.TrabajadorClass;
import com.mycompany.Luxcar.Utilidades;
import com.mycompany.Util.Glasspanepopup.DefaultOption;
import com.mycompany.Util.Glasspanepopup.GlassPanePopup;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class PopupVerRegistroTrabajador extends javax.swing.JPanel {

    public PopupVerRegistroTrabajador() {
        initComponents();
        InicializarTablaServicio();
        CargarImagenDefault();
        TITTLE.setIcon(new FlatSVGIcon("svg/worker.svg",70,70));

        GlassPanePopup.showPopup(this, new DefaultOption() {
            @Override
            public boolean closeWhenClickOutside() {
                return true;
            }

            @Override
            public boolean closeWhenPressedEsc() {
                return true;
            }

            @Override
            public Color background() {
                return new Color(0, 0, 0);
            }

            @Override
            public int duration() {
                return 100;
            }
        });
    }

    public PopupVerRegistroTrabajador(TrabajadorClass Trabajador) {
        this();

        NOMBRES_APELLIDOS.setText(Trabajador.getNombresApellidos());
        DIRECCION.setText(Trabajador.getDireccion());
        DNI.setText(Trabajador.getDNI());
        CORREO.setText(Trabajador.getCorreo());
        PUESTO.setText(Trabajador.getPuesto());
        TELEFONO.setText(Utilidades.setNumerox9_51(Trabajador.getTelefono()));
        GENERO.setText(Trabajador.getGenero());
        
        if(Trabajador.getFoto() == null){
            CargarImagenDefault();
        }else{
            try {
                IMAGEN.setBackground_Image( Utilidades.bytesToImageIcon(Trabajador.getFoto()));
            } catch (IOException ex) {
                Logger.getLogger(PopupModificarTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

        ControlServicio cs = new ControlServicio();
        DefaultTableModel service_model = cs.getAllServiceTrabajador(Trabajador.getDNI(), (DefaultTableModel) TABLA_SERVICIO.getModel());
        TABLA_SERVICIO.setModel(service_model);

    }

    public void CargarImagenDefault() {
        IMAGEN.setBackground_Image(new FlatSVGIcon("svg/photo.svg", 150, 150));
    }

    public void InicializarTablaServicio() {

        DefaultTableModel Model = (DefaultTableModel) TABLA_SERVICIO.getModel();

        TABLA_SERVICIO.setHorizontalTextPositionHeader(new int[]{
            SwingConstants.CENTER,
            SwingConstants.CENTER,
            SwingConstants.LEFT,
            SwingConstants.CENTER
        });
        TABLA_SERVICIO.setHorizontalTextPosition(new int[]{
            SwingConstants.CENTER,
            SwingConstants.CENTER,
            SwingConstants.LEFT,
            SwingConstants.CENTER
        });
        TABLA_SERVICIO.FixScroll(jScrollPane1);
        TABLA_SERVICIO.setModel(Model);
        /*
        TABLA_SERVICIO.setColumnWidths(new int[]{
            40,//1 DNI
            130,//2 Nombres
            130,//3 Apellidos
            130//9 Puesto

        });*/

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new com.mycompany.Swing.Panel.Panel();
        panel2 = new com.mycompany.Swing.Panel.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_SERVICIO = new com.mycompany.Swing.Tabla.Tabla();
        panel3 = new com.mycompany.Swing.Panel.Panel();
        DNI = new javax.swing.JLabel();
        DNI1 = new javax.swing.JLabel();
        TITTLE = new com.mycompany.Swing.Label.LabelIcon();
        jLabel1 = new javax.swing.JLabel();
        IMAGEN = new com.mycompany.Swing.Background.Background_Img();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NOMBRES_APELLIDOS = new com.mycompany.Swing.TextField.TextField();
        DIRECCION = new com.mycompany.Swing.TextField.TextField();
        CORREO = new com.mycompany.Swing.TextField.TextField();
        TELEFONO = new com.mycompany.Swing.TextField.TextField();
        PUESTO = new com.mycompany.Swing.TextField.TextField();
        GENERO = new com.mycompany.Swing.TextField.TextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setOpaque(false);

        panel1.setBackground(new java.awt.Color(250, 250, 255));
        panel1.setPanel_Round(7);
        panel1.setPanel_ShadowOpacity(0.3F);
        panel1.setPanel_ShadowSize(3);

        panel2.setPanel_Round(7);
        panel2.setPanel_ShadowOpacity(0.3F);
        panel2.setPanel_ShadowSize(3);

        TABLA_SERVICIO.setBorder(null);
        TABLA_SERVICIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N°", "ID Servicio", "Ubicaion", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLA_SERVICIO.setHeader_BackgroundColor(new java.awt.Color(16, 78, 128));
        TABLA_SERVICIO.setHeader_BorderActived(false);
        TABLA_SERVICIO.setHeader_ForegroundColor(new java.awt.Color(255, 255, 255));
        TABLA_SERVICIO.setHeader_Round(15);
        TABLA_SERVICIO.setRowHeight(33);
        TABLA_SERVICIO.setRow_SelectedColor(new java.awt.Color(255, 255, 255));
        TABLA_SERVICIO.setTable_GridLineColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(TABLA_SERVICIO);
        if (TABLA_SERVICIO.getColumnModel().getColumnCount() > 0) {
            TABLA_SERVICIO.getColumnModel().getColumn(0).setResizable(false);
            TABLA_SERVICIO.getColumnModel().getColumn(0).setPreferredWidth(10);
            TABLA_SERVICIO.getColumnModel().getColumn(1).setResizable(false);
            TABLA_SERVICIO.getColumnModel().getColumn(1).setPreferredWidth(100);
            TABLA_SERVICIO.getColumnModel().getColumn(2).setResizable(false);
            TABLA_SERVICIO.getColumnModel().getColumn(2).setPreferredWidth(400);
            TABLA_SERVICIO.getColumnModel().getColumn(3).setResizable(false);
            TABLA_SERVICIO.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1)
                .addGap(5, 5, 5))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        panel3.setPanel_BackgroundGradientActived(true);
        panel3.setPanel_BackgroundGradientColor1(new java.awt.Color(16, 78, 128));
        panel3.setPanel_BackgroundGradientColor2(new java.awt.Color(36, 98, 128));
        panel3.setPanel_Round(7);
        panel3.setPanel_ShadowOpacity(0.3F);
        panel3.setPanel_ShadowSize(3);

        DNI.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        DNI.setForeground(new java.awt.Color(255, 255, 255));
        DNI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNI.setText("12345678");

        DNI1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        DNI1.setForeground(new java.awt.Color(255, 255, 255));
        DNI1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNI1.setText("DNI:");

        TITTLE.setForeground(new java.awt.Color(255, 255, 255));
        TITTLE.setText("REGISTRO DEL TRABAJADOR");
        TITTLE.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        TITTLE.setIconColorFilterActived(true);

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(TITTLE, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNI1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(TITTLE, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37))
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 78, 128));
        jLabel1.setText("Servicios totales del trabajdor");

        IMAGEN.setBackground_BorderActived(true);
        IMAGEN.setBackground_BorderColor(new java.awt.Color(16, 78, 128));
        IMAGEN.setBackground_ImageOpacity(0.0F);
        IMAGEN.setBackground_ImgMaxMin(true);

        javax.swing.GroupLayout IMAGENLayout = new javax.swing.GroupLayout(IMAGEN);
        IMAGEN.setLayout(IMAGENLayout);
        IMAGENLayout.setHorizontalGroup(
            IMAGENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        IMAGENLayout.setVerticalGroup(
            IMAGENLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 272, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(16, 78, 128));
        jLabel2.setText("Datos del trabajador");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Nombres y apellidos: ");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("Direccion:");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Puesto: ");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("Telefono: ");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Genero:");

        NOMBRES_APELLIDOS.setEditable(false);
        NOMBRES_APELLIDOS.setFocusable(false);
        NOMBRES_APELLIDOS.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        NOMBRES_APELLIDOS.setTextField_BorderActived(true);
        NOMBRES_APELLIDOS.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        NOMBRES_APELLIDOS.setTextField_Round(7);
        NOMBRES_APELLIDOS.setTextField_ShadowOpacity(0.3F);
        NOMBRES_APELLIDOS.setTextField_ShadowSize(3);

        DIRECCION.setEditable(false);
        DIRECCION.setFocusable(false);
        DIRECCION.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        DIRECCION.setTextField_BorderActived(true);
        DIRECCION.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        DIRECCION.setTextField_Round(7);
        DIRECCION.setTextField_ShadowOpacity(0.3F);
        DIRECCION.setTextField_ShadowSize(3);

        CORREO.setEditable(false);
        CORREO.setFocusable(false);
        CORREO.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        CORREO.setTextField_BorderActived(true);
        CORREO.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        CORREO.setTextField_Round(7);
        CORREO.setTextField_ShadowOpacity(0.3F);
        CORREO.setTextField_ShadowSize(3);

        TELEFONO.setEditable(false);
        TELEFONO.setFocusable(false);
        TELEFONO.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        TELEFONO.setTextField_BorderActived(true);
        TELEFONO.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        TELEFONO.setTextField_Round(7);
        TELEFONO.setTextField_ShadowOpacity(0.3F);
        TELEFONO.setTextField_ShadowSize(3);
        TELEFONO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TELEFONOActionPerformed(evt);
            }
        });

        PUESTO.setEditable(false);
        PUESTO.setFocusable(false);
        PUESTO.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        PUESTO.setTextField_BorderActived(true);
        PUESTO.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        PUESTO.setTextField_Round(7);
        PUESTO.setTextField_ShadowOpacity(0.3F);
        PUESTO.setTextField_ShadowSize(3);

        GENERO.setEditable(false);
        GENERO.setFocusable(false);
        GENERO.setFont(new java.awt.Font("sansserif", 1, 16)); // NOI18N
        GENERO.setTextField_BorderActived(true);
        GENERO.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        GENERO.setTextField_Round(7);
        GENERO.setTextField_ShadowOpacity(0.3F);
        GENERO.setTextField_ShadowSize(3);

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(16, 78, 128));
        jLabel11.setText("Foto");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11)
                    .addComponent(IMAGEN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator2)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(NOMBRES_APELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TELEFONO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CORREO, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NOMBRES_APELLIDOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DIRECCION, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(GENERO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CORREO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(PUESTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(IMAGEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TELEFONOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TELEFONOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TELEFONOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.TextField.TextField CORREO;
    private com.mycompany.Swing.TextField.TextField DIRECCION;
    private javax.swing.JLabel DNI;
    private javax.swing.JLabel DNI1;
    private com.mycompany.Swing.TextField.TextField GENERO;
    private com.mycompany.Swing.Background.Background_Img IMAGEN;
    private com.mycompany.Swing.TextField.TextField NOMBRES_APELLIDOS;
    private com.mycompany.Swing.TextField.TextField PUESTO;
    private com.mycompany.Swing.Tabla.Tabla TABLA_SERVICIO;
    private com.mycompany.Swing.TextField.TextField TELEFONO;
    private com.mycompany.Swing.Label.LabelIcon TITTLE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private com.mycompany.Swing.Panel.Panel panel1;
    private com.mycompany.Swing.Panel.Panel panel2;
    private com.mycompany.Swing.Panel.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
