package com.mycompany.LuxcarForm.FormsUsuario;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.mycompany.DataBase.Control.ControlUsuario;
import com.mycompany.DataBase.Control.TrabajadorClass;
import com.mycompany.DataBase.Control.UsuarioClass;
import com.mycompany.LuxcarForm.FormUsuario;
import com.mycompany.Popup.PopupMessage;
import com.mycompany.Util.Glasspanepopup.DefaultOption;
import com.mycompany.Util.Glasspanepopup.GlassPanePopup;
import java.awt.Color;

/**
 *
 * @author ricar
 */
public class PopupCrearUsuario extends javax.swing.JPanel {

    public PopupCrearUsuario() {
        initComponents();
        BTN_VIEW_PASSWORD.setIcon(new FlatSVGIcon("svg/no_ver_contraseña.svg", 25, 25));
        GlassPanePopup.showPopup(this, new DefaultOption() {
            @Override
            public Color background() {
                return new Color(0, 0, 0);
            }

        });
    }

    public PopupCrearUsuario(TrabajadorClass Trabajador) {
        this();
        DNI_TRABAJADOR.setText(Trabajador.getDNI());
        NOMBRES_APELLIDOS_TRABAJADOR.setText(Trabajador.getNombresApellidos());
    }

    public boolean ValidarDatos() {

        if (getContraseña().equals("")) {
            new PopupMessage("CONTRASEÑA", "El campo contraseña esta vacio.", 2);
            return false;
        } else if (getConfirContraseña().equals("")) {
            new PopupMessage("CONFIRMAR CONTRASEÑA", "El campo confirmar contraseña esta vacio.", 2);
            return false;
        } else if (getContraseña().length() < 5) {
            new PopupMessage("CONTRASEÑA", "La contraseña es muy corta.", 2);
            return false;
        } else if (!getContraseña().equals(getConfirContraseña())) {
            new PopupMessage("CONTRASEÑA", "Las contraseñas no coinciden", 2);
            return false;
        } else {
            return true;
        }
    }

    public String getContraseña() {
        return CONTRASENIA.getText();
    }

    public String getConfirContraseña() {
        return CONFIR_CONTRASEÑA.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new com.mycompany.Swing.Panel.Panel();
        panel2 = new com.mycompany.Swing.Panel.Panel();
        DNI_TRABAJADOR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NOMBRES_APELLIDOS_TRABAJADOR = new javax.swing.JLabel();
        BTN_CANCELAR = new com.mycompany.Swing.Button.Button();
        BTN_GUARDAR = new com.mycompany.Swing.Button.Button();
        jPanel1 = new javax.swing.JPanel();
        CONTRASENIA = new com.mycompany.Swing.TextField.PasswordField();
        CONFIR_CONTRASEÑA = new com.mycompany.Swing.TextField.PasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BTN_VIEW_PASSWORD = new com.mycompany.Swing.Button.Button();

        setOpaque(false);

        panel1.setBackground(new java.awt.Color(250, 250, 255));

        panel2.setPanel_BackgroundGradientActived(true);
        panel2.setPanel_BackgroundGradientColor1(new java.awt.Color(16, 78, 128));
        panel2.setPanel_BackgroundGradientColor2(new java.awt.Color(46, 98, 128));
        panel2.setPanel_Round(7);

        DNI_TRABAJADOR.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        DNI_TRABAJADOR.setForeground(new java.awt.Color(255, 255, 255));
        DNI_TRABAJADOR.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNI_TRABAJADOR.setText("12345678");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Crar Usuario");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DNI_TRABAJADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNI_TRABAJADOR, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Trabajador");

        NOMBRES_APELLIDOS_TRABAJADOR.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NOMBRES_APELLIDOS_TRABAJADOR.setForeground(new java.awt.Color(153, 153, 153));
        NOMBRES_APELLIDOS_TRABAJADOR.setText("Nombres y apellidos del trabajador.");

        BTN_CANCELAR.setText("Cancelar");
        BTN_CANCELAR.setButton_Round(7);
        BTN_CANCELAR.setButton_ShadowSize(3);
        BTN_CANCELAR.setButton_ShawdowOpacity(0.3F);
        BTN_CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CANCELARActionPerformed(evt);
            }
        });

        BTN_GUARDAR.setBackground(new java.awt.Color(16, 78, 128));
        BTN_GUARDAR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_GUARDAR.setText("Crear");
        BTN_GUARDAR.setButton_BackgroundColorEntered(new java.awt.Color(38, 98, 128));
        BTN_GUARDAR.setButton_Round(7);
        BTN_GUARDAR.setButton_ShadowSize(3);
        BTN_GUARDAR.setButton_ShawdowOpacity(0.3F);
        BTN_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_GUARDARActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);

        CONTRASENIA.setTextField_BorderActived(true);
        CONTRASENIA.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        CONTRASENIA.setTextField_Round(7);
        CONTRASENIA.setTextField_ShadowOpacity(0.3F);
        CONTRASENIA.setTextField_ShadowSize(3);
        CONTRASENIA.setTextField_Txthint("Ingrese su contraseña");
        CONTRASENIA.setTextField_TxthintColor(new java.awt.Color(153, 153, 153));

        CONFIR_CONTRASEÑA.setTextField_BorderActived(true);
        CONFIR_CONTRASEÑA.setTextField_BorderColor(new java.awt.Color(204, 204, 204));
        CONFIR_CONTRASEÑA.setTextField_Round(7);
        CONFIR_CONTRASEÑA.setTextField_ShadowOpacity(0.3F);
        CONFIR_CONTRASEÑA.setTextField_ShadowSize(3);
        CONFIR_CONTRASEÑA.setTextField_Txthint("Confirmar contraseña");
        CONFIR_CONTRASEÑA.setTextField_TxthintColor(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Contraseña");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Confirmar contraseña");

        BTN_VIEW_PASSWORD.setButton_ActivedBackground(false);
        BTN_VIEW_PASSWORD.setButton_ActivedIconColorFilter(true);
        BTN_VIEW_PASSWORD.setButton_IconColorFilter(new java.awt.Color(51, 51, 51));
        BTN_VIEW_PASSWORD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTN_VIEW_PASSWORDMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                BTN_VIEW_PASSWORDMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CONFIR_CONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(CONTRASENIA, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_VIEW_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CONTRASENIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_VIEW_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(CONFIR_CONTRASEÑA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(NOMBRES_APELLIDOS_TRABAJADOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                        .addComponent(BTN_CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTN_GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addComponent(panel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(NOMBRES_APELLIDOS_TRABAJADOR)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_CANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_GUARDAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CANCELARActionPerformed
        // TODO add your handling code here:
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_BTN_CANCELARActionPerformed

    private void BTN_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_GUARDARActionPerformed
        // TODO add your handling code here:
        if (ValidarDatos()) {

            ControlUsuario cu = new ControlUsuario();
            UsuarioClass u = new UsuarioClass(DNI_TRABAJADOR.getText(), getContraseña(), false);
            cu.InsertarUsuario(u);
            cu.Disconneting();

            FormUsuario.getCountUsers();
            FormUsuario.DataUsuario.MostrarBusquedaDeTrabajadorSinUsuario(FormUsuario.TXT_BUSQUEDA.getText());
            
            GlassPanePopup.closePopupLast();
            new PopupMessage(
                    "¡ CREACION DE USUARIO EXITOSO !",
                    "Se ha cambiado correctamente la contraseña del usuario",
                    0
            );

        }

    }//GEN-LAST:event_BTN_GUARDARActionPerformed

    private void BTN_VIEW_PASSWORDMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_VIEW_PASSWORDMousePressed
        BTN_VIEW_PASSWORD.setIcon(new FlatSVGIcon("svg/ver_contraseña.svg", 25, 25));
        CONTRASENIA.setEchoChar((char) 0);
        CONFIR_CONTRASEÑA.setEchoChar((char) 0);
    }//GEN-LAST:event_BTN_VIEW_PASSWORDMousePressed

    private void BTN_VIEW_PASSWORDMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_VIEW_PASSWORDMouseReleased
        BTN_VIEW_PASSWORD.setIcon(new FlatSVGIcon("svg/no_ver_contraseña.svg", 25, 25));
        CONTRASENIA.setEchoChar('•');
        CONFIR_CONTRASEÑA.setEchoChar('•');
    }//GEN-LAST:event_BTN_VIEW_PASSWORDMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.Swing.Button.Button BTN_CANCELAR;
    private com.mycompany.Swing.Button.Button BTN_GUARDAR;
    private com.mycompany.Swing.Button.Button BTN_VIEW_PASSWORD;
    private com.mycompany.Swing.TextField.PasswordField CONFIR_CONTRASEÑA;
    private com.mycompany.Swing.TextField.PasswordField CONTRASENIA;
    private javax.swing.JLabel DNI_TRABAJADOR;
    private javax.swing.JLabel NOMBRES_APELLIDOS_TRABAJADOR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private com.mycompany.Swing.Panel.Panel panel1;
    private com.mycompany.Swing.Panel.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
