/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Factura;

import Swing.table.Objeto.Data;
import com.formdev.flatlaf.extras.FlatSVGIcon;

/**
 *
 * @author ricar
 */
public class FACTURA extends javax.swing.JPanel {

    
    /**
     * Creates new form FACTURA
     */
    
    
    public FACTURA() {
        initComponents();
        table.fixTable(jScrollPane1);
       
            table.addRow(new Data("1", "asd", "123", 100).toRowTable(null));
            table.addRow(new Data("2", "asd", "123", 200).toRowTable(null));
            table.addRow(new Data("3", "asd", "123", 300).toRowTable(null));
            table.addRow(new Data("4", "Maale", "123", 400).toRowTable(null));
            table.addRow(new Data("5", "asd", "123123", 500).toRowTable(null));
            table.addRow(new Data("6", "asd", "123", 600).toRowTable(null));
            table.addRow(new Data("7", "asd", "123123", 700).toRowTable(null));
            table.addRow(new Data("8", "asd", "123", 800).toRowTable(null));
            table.addRow(new Data("9", "asd", "123123", 700).toRowTable(null));
            table.addRow(new Data("10", "asd", "123", 800).toRowTable(null));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new Swing.Panel.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbCodigo5 = new javax.swing.JLabel();
        lbCodigo6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ICON = new javax.swing.JLabel();
        lbCodigo7 = new javax.swing.JLabel();
        lbCodigo8 = new javax.swing.JLabel();
        lbCodigo9 = new javax.swing.JLabel();
        lbCodigo10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbCodigo3 = new javax.swing.JLabel();
        lbCodigo1 = new javax.swing.JLabel();
        lbCodigo4 = new javax.swing.JLabel();
        lbCodigo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new Swing.table.TableComprobante();
        jPanel5 = new Swing.Panel.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setPanel_BorderActived(true);
        jPanel1.setPanel_BorderColor(new java.awt.Color(204, 204, 204));
        jPanel1.setPanel_Round(20);
        jPanel1.setPanel_ShadowSize(1);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbCodigo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(102, 102, 102));
        lbCodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo.setText("EB-0001");
        jPanel1.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 78, 130, -1));

        lbCodigo5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbCodigo5.setForeground(new java.awt.Color(102, 102, 102));
        lbCodigo5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo5.setText("R.U.C. 1234567890");
        jPanel1.add(lbCodigo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 245, -1));

        lbCodigo6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbCodigo6.setForeground(new java.awt.Color(255, 255, 255));
        lbCodigo6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo6.setText("FACTURA");
        jPanel1.add(lbCodigo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 42, 130, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 34, 248, 40));

        ICON.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Factura/company.png"))); // NOI18N
        ICON.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lbCodigo7.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        lbCodigo7.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo7.setText("\"Don bigote.com xd\"");

        lbCodigo8.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo8.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo8.setText("Esta es una tienda de no se que");

        lbCodigo9.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo9.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo9.setText("Direccion av.asdasdasd");

        lbCodigo10.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo10.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCodigo10.setText("Telf.123123123");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ICON)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbCodigo7, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCodigo8, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCodigo10, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCodigo9, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ICON, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbCodigo7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigo8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigo9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigo10)))
                .addGap(20, 20, 20))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lbCodigo3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo3.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo3.setText("Señor (es):");

        lbCodigo1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo1.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo1.setText("Dirección:");

        lbCodigo4.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo4.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo4.setText("R.U.C:");

        lbCodigo2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lbCodigo2.setForeground(new java.awt.Color(51, 51, 51));
        lbCodigo2.setText("Pucallpa, 15 de Julio del 2024.");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCodigo3, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(lbCodigo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 273, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbCodigo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(315, 315, 315))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(lbCodigo2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo3)
                    .addComponent(lbCodigo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo1)
                    .addComponent(lbCodigo2))
                .addGap(10, 10, 10))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Descripción", "Precio Unitario", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(1).setPreferredWidth(400);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(100);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(3).setPreferredWidth(100);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ICON;
    private Swing.Panel.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private Swing.Panel.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigo1;
    private javax.swing.JLabel lbCodigo10;
    private javax.swing.JLabel lbCodigo2;
    private javax.swing.JLabel lbCodigo3;
    private javax.swing.JLabel lbCodigo4;
    private javax.swing.JLabel lbCodigo5;
    private javax.swing.JLabel lbCodigo6;
    private javax.swing.JLabel lbCodigo7;
    private javax.swing.JLabel lbCodigo8;
    private javax.swing.JLabel lbCodigo9;
    private Swing.table.TableComprobante table;
    // End of variables declaration//GEN-END:variables
}
