/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Swing.table;

import Mesaage.ConfDelete;
import Mesaage.EditItem;
import Mesaage.ViewItem;
import Swing.table.AuxAction.EventAction;
import Swing.table.Objeto.Data;
import Util.Glasspanepopup.GlassPanePopup;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author ricar
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
        initTableData();
        
    }
    private void initTableData() {

        table.fixTable(jScrollPane1);

        EventAction eventAction = new EventAction() {
            @Override
            public void delete(Data student) {
                System.out.println("Delete");
                /*
                if (table.isEditing()) {
                    table.getCellEditor().stopCellEditing();
                }
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                model.removeRow(row);
                 */
                ConfDelete obj = new ConfDelete();

                //Pasardatos
                obj.setTextName(student.getName());
                //Pasardatos

                obj.eventOK(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {

                        /*Elimancion de datos Confirmado
                        
                        DefaultTableModel modelo = (DefaultTableModel) table1.getModel();
                        int filaAEliminar = 0; 
                        modelo.removeRow(filaAEliminar);*/
                        GlassPanePopup.closePopupLast();

                    }
                });
                GlassPanePopup.showPopup(obj);
            }

            @Override
            public void update(Data student) {

                System.out.println("Update");

                EditItem obj = new EditItem();
                //Pasardatos
                obj.setTextName(student.getName());
                //Pasardatos

                obj.eventOK(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent ae) {

                        //Guardar datos actualizados
                        GlassPanePopup.closePopupLast();
                    }
                });

                GlassPanePopup.showPopup(obj);

            }

            @Override
            public void view(Data student) {
                System.out.println("View");

                ViewItem obj = new ViewItem();
                //Pasardatos
                obj.setTxt(student.getName());
                //Pasardatos

                GlassPanePopup.showPopup(obj);
            }
        };

        for (int i = 0; i < 1; i++) {
            table.addRow(new Data("1", "asd", "123", 100).toRowTable(eventAction));
            table.addRow(new Data("2", "asd", "123", 200).toRowTable(eventAction));
            table.addRow(new Data("3", "asd", "123", 300).toRowTable(eventAction));
            table.addRow(new Data("4", "Maale", "123", 400).toRowTable(eventAction));
            table.addRow(new Data("5", "asd", "123123", 500).toRowTable(eventAction));
            table.addRow(new Data("6", "asd", "123", 600).toRowTable(eventAction));
            table.addRow(new Data("7", "asd", "123123", 700).toRowTable(eventAction));
            table.addRow(new Data("8", "asd", "123", 800).toRowTable(eventAction));

        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new Swing.table.Table();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private Swing.table.Table table;
    // End of variables declaration//GEN-END:variables

}
