/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.LuxcarDocuments;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ricar
 */
public class Document extends javax.swing.JPanel implements Printable {

    /**
     * Creates new form Document
     */
    public Document() {
        initComponents();
        InicializarTabla();

    }

    public void InicializarTabla() {

        TABLA_1.setHorizontalTextPosition(new int[]{
            SwingConstants.CENTER,//1 
            SwingConstants.CENTER,//2 
            SwingConstants.LEFT,//3 
            SwingConstants.CENTER,//4 
            SwingConstants.CENTER,//5 
            SwingConstants.CENTER//6 
        });
        /*
        DefaultTableModel Model = new DefaultTableModel(null, TextHeader) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };*/

        TABLA_1.FixScroll(jScrollPane1);
        TABLA_2.FixScroll(jScrollPane2);
        TABLA_3.FixScroll(jScrollPane3);
        //TABLA_1.setHeader_Border(new EmptyBorder(19, 1, 19, 1));

        //TABLA_1.setModel(Model);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel6 = new com.mycompany.Swing.Panel.Panel();
        jLabel29 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        UBICACION_SERVICIO = new javax.swing.JLabel();
        panel7 = new com.mycompany.Swing.Panel.Panel();
        jLabel20 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        panel10 = new com.mycompany.Swing.Panel.Panel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        panel27 = new com.mycompany.Swing.Panel.Panel();
        jLabel18 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        panel17 = new com.mycompany.Swing.Panel.Panel();
        jLabel22 = new javax.swing.JLabel();
        panel11 = new com.mycompany.Swing.Panel.Panel();
        jLabel11 = new javax.swing.JLabel();
        panel28 = new com.mycompany.Swing.Panel.Panel();
        jLabel81 = new javax.swing.JLabel();
        panel22 = new com.mycompany.Swing.Panel.Panel();
        FECHA_FINALIZACION_SERVICIO = new javax.swing.JLabel();
        panel24 = new com.mycompany.Swing.Panel.Panel();
        DESCRIPCION_SERVICIO = new javax.swing.JLabel();
        panel25 = new com.mycompany.Swing.Panel.Panel();
        FECHA_INICIO_SERVICIO = new javax.swing.JLabel();
        panel15 = new com.mycompany.Swing.Panel.Panel();
        panel20 = new com.mycompany.Swing.Panel.Panel();
        panel21 = new com.mycompany.Swing.Panel.Panel();
        jLabel6 = new javax.swing.JLabel();
        panel29 = new com.mycompany.Swing.Panel.Panel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLA_1 = new com.mycompany.Swing.Tabla.Tabla();
        panel30 = new com.mycompany.Swing.Panel.Panel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TABLA_2 = new com.mycompany.Swing.Tabla.Tabla();
        panel31 = new com.mycompany.Swing.Panel.Panel();
        jLabel95 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TABLA_3 = new com.mycompany.Swing.Tabla.Tabla();
        panel32 = new com.mycompany.Swing.Panel.Panel();
        jLabel96 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        panel33 = new com.mycompany.Swing.Panel.Panel();
        jLabel100 = new javax.swing.JLabel();
        panel34 = new com.mycompany.Swing.Panel.Panel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        panel35 = new com.mycompany.Swing.Panel.Panel();
        jTextArea1 = new javax.swing.JTextArea();
        panel36 = new com.mycompany.Swing.Panel.Panel();
        panel37 = new com.mycompany.Swing.Panel.Panel();
        jLabel101 = new javax.swing.JLabel();
        panel38 = new com.mycompany.Swing.Panel.Panel();
        panel39 = new com.mycompany.Swing.Panel.Panel();
        jLabel102 = new javax.swing.JLabel();
        panel40 = new com.mycompany.Swing.Panel.Panel();
        panel41 = new com.mycompany.Swing.Panel.Panel();
        jLabel103 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        panel2 = new com.mycompany.Swing.Panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        panel3 = new com.mycompany.Swing.Panel.Panel();
        jLabel9 = new javax.swing.JLabel();
        panel4 = new com.mycompany.Swing.Panel.Panel();
        IDSERVICIO = new javax.swing.JLabel();
        panel5 = new com.mycompany.Swing.Panel.Panel();
        jLabel5 = new javax.swing.JLabel();
        panel8 = new com.mycompany.Swing.Panel.Panel();
        jLabel8 = new javax.swing.JLabel();
        panel9 = new com.mycompany.Swing.Panel.Panel();
        DIA_SERVICIO = new javax.swing.JLabel();
        background_Img1 = new com.mycompany.Swing.Background.Background_Img();
        jLabel2 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);

        panel6.setPanel_BorderActived(true);
        panel6.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel6.setPanel_Round(0);
        panel6.setPanel_ShadowOpacity(0.0F);
        panel6.setPanel_ShadowSize(0);

        jLabel29.setBackground(new java.awt.Color(255, 0, 0));
        jLabel29.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("HOSPITAL II-PUCALLPA");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel23.setText("CENTRO  A SISTENCIAL : ");

        jLabel24.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel24.setText("UBICACION FISICA: ");

        jLabel25.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel25.setText("ORGANO  DESCONCENTRADO : ");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel27.setText("SERVICIO HOSPITALARIO: ");

        UBICACION_SERVICIO.setBackground(new java.awt.Color(255, 0, 0));
        UBICACION_SERVICIO.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        UBICACION_SERVICIO.setForeground(new java.awt.Color(51, 51, 255));
        UBICACION_SERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UBICACION_SERVICIO.setText("UBICACION SERVICIO");

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel6Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(5, 5, 5)
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel6Layout.createSequentialGroup()
                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UBICACION_SERVICIO, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel25)
                .addGap(3, 3, 3)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(UBICACION_SERVICIO))
                .addGap(7, 7, 7))
        );

        panel7.setPanel_BorderActived(true);
        panel7.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel7.setPanel_Round(0);
        panel7.setPanel_ShadowOpacity(0.0F);
        panel7.setPanel_ShadowSize(0);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel20.setText("DENOMINACION DEL AMBIENTE / AREA COMUN / INSTALACION: ");

        jLabel80.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel80.setText("CODIGO DE AMBIENTE / AREA COMUN / INSTALACION: ");

        javax.swing.GroupLayout panel7Layout = new javax.swing.GroupLayout(panel7);
        panel7.setLayout(panel7Layout);
        panel7Layout.setHorizontalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174)
                .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel7Layout.setVerticalGroup(
            panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel80))
                .addGap(7, 7, 7))
        );

        panel10.setPanel_BorderActived(true);
        panel10.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel10.setPanel_Round(0);
        panel10.setPanel_ShadowOpacity(0.0F);
        panel10.setPanel_ShadowSize(0);

        jLabel55.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel55.setText("MODALIDAD DE EJECUCION: ");

        jLabel56.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(0, 204, 0));
        jLabel56.setText("RR.HH PROPIOS / SERVICIO-MANO DE OBRA / SERVICIO A TODO COSTO");

        jLabel70.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel70.setText("EJECUTOR DE LA ACTIVIDAD: ");

        jLabel71.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(0, 204, 0));
        jLabel71.setText("PREVENTIVO / CORRECTIVO");

        jLabel72.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel72.setText("TIPO DE MANTENIMIENTO: ");

        jLabel73.setBackground(new java.awt.Color(255, 0, 0));
        jLabel73.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(51, 51, 51));
        jLabel73.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel73.setText("LUXCAR SERVICIOS GENERALES");

        javax.swing.GroupLayout panel10Layout = new javax.swing.GroupLayout(panel10);
        panel10.setLayout(panel10Layout);
        panel10Layout.setHorizontalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel10Layout.createSequentialGroup()
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel10Layout.createSequentialGroup()
                        .addComponent(jLabel71, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel70, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel73, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel10Layout.setVerticalGroup(
            panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel10Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel71)
                    .addComponent(jLabel70)
                    .addComponent(jLabel73))
                .addGap(3, 3, 3)
                .addGroup(panel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel55, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel56, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        panel27.setPanel_BorderActived(true);
        panel27.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel27.setPanel_Round(0);
        panel27.setPanel_ShadowOpacity(0.0F);
        panel27.setPanel_ShadowSize(0);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel18.setText("CAUSA DEL DAÑO");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 204, 0));
        jLabel30.setText("FISICO / MECANICO / QUIMICO / BIOLÓGICO / OTROS / NINGUNO");

        jLabel32.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 204, 0));
        jLabel32.setText("BUENO / REGULAR / MALO");

        jLabel33.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel33.setText("ESTADO INICIAL DE LA INSTRAESTRUCTURA O INSTALACION: ");

        jLabel44.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel44.setText("TIPO DE DAÑO: ");

        javax.swing.GroupLayout panel27Layout = new javax.swing.GroupLayout(panel27);
        panel27.setLayout(panel27Layout);
        panel27Layout.setHorizontalGroup(
            panel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel27Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel27Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel27Layout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel27Layout.setVerticalGroup(
            panel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel27Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel32))
                .addGap(3, 3, 3)
                .addGroup(panel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(jLabel30)
                    .addComponent(jLabel18))
                .addGap(7, 7, 7))
        );

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel17.setBackground(new java.awt.Color(204, 255, 255));
        panel17.setPanel_BorderActived(true);
        panel17.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel17.setPanel_Round(0);
        panel17.setPanel_ShadowOpacity(0.0F);
        panel17.setPanel_ShadowSize(0);

        jLabel22.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("FECHA DE SOLICITUD");

        javax.swing.GroupLayout panel17Layout = new javax.swing.GroupLayout(panel17);
        panel17.setLayout(panel17Layout);
        panel17Layout.setHorizontalGroup(
            panel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel17Layout.setVerticalGroup(
            panel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(panel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        panel11.setBackground(new java.awt.Color(204, 255, 255));
        panel11.setPanel_BorderActived(true);
        panel11.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel11.setPanel_Round(0);
        panel11.setPanel_ShadowOpacity(0.0F);
        panel11.setPanel_ShadowSize(0);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("DESCRIPCION DE LA SOLICITUD DE TRABAJDO O DEL DAÑO DE LA INFRAESTRUCTURA O INSTALACION");

        javax.swing.GroupLayout panel11Layout = new javax.swing.GroupLayout(panel11);
        panel11.setLayout(panel11Layout);
        panel11Layout.setHorizontalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        panel11Layout.setVerticalGroup(
            panel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel3.add(panel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 710, -1));

        panel28.setBackground(new java.awt.Color(204, 255, 255));
        panel28.setPanel_BorderActived(true);
        panel28.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel28.setPanel_Round(0);
        panel28.setPanel_ShadowOpacity(0.0F);
        panel28.setPanel_ShadowSize(0);

        jLabel81.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("FECHA DE CONFORMIDAD");

        javax.swing.GroupLayout panel28Layout = new javax.swing.GroupLayout(panel28);
        panel28.setLayout(panel28Layout);
        panel28Layout.setHorizontalGroup(
            panel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel28Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel28Layout.setVerticalGroup(
            panel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel28Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel81, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(panel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 250, -1));

        panel22.setPanel_BorderActived(true);
        panel22.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel22.setPanel_Round(0);
        panel22.setPanel_ShadowOpacity(0.0F);
        panel22.setPanel_ShadowSize(0);

        FECHA_FINALIZACION_SERVICIO.setBackground(new java.awt.Color(255, 0, 0));
        FECHA_FINALIZACION_SERVICIO.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        FECHA_FINALIZACION_SERVICIO.setForeground(new java.awt.Color(51, 51, 255));
        FECHA_FINALIZACION_SERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FECHA_FINALIZACION_SERVICIO.setText("FECHA");

        javax.swing.GroupLayout panel22Layout = new javax.swing.GroupLayout(panel22);
        panel22.setLayout(panel22Layout);
        panel22Layout.setHorizontalGroup(
            panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel22Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(FECHA_FINALIZACION_SERVICIO, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        panel22Layout.setVerticalGroup(
            panel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FECHA_FINALIZACION_SERVICIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(panel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 250, 40));

        panel24.setPanel_BorderActived(true);
        panel24.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel24.setPanel_Round(0);
        panel24.setPanel_ShadowOpacity(0.0F);
        panel24.setPanel_ShadowSize(0);

        DESCRIPCION_SERVICIO.setBackground(new java.awt.Color(255, 0, 0));
        DESCRIPCION_SERVICIO.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DESCRIPCION_SERVICIO.setForeground(new java.awt.Color(51, 51, 255));
        DESCRIPCION_SERVICIO.setText("DESCRIPCION DE LA SOLICITUD");

        javax.swing.GroupLayout panel24Layout = new javax.swing.GroupLayout(panel24);
        panel24.setLayout(panel24Layout);
        panel24Layout.setHorizontalGroup(
            panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel24Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DESCRIPCION_SERVICIO, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel24Layout.setVerticalGroup(
            panel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DESCRIPCION_SERVICIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(panel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 710, 40));

        panel25.setPanel_BorderActived(true);
        panel25.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel25.setPanel_Round(0);
        panel25.setPanel_ShadowOpacity(0.0F);
        panel25.setPanel_ShadowSize(0);

        FECHA_INICIO_SERVICIO.setBackground(new java.awt.Color(255, 0, 0));
        FECHA_INICIO_SERVICIO.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        FECHA_INICIO_SERVICIO.setForeground(new java.awt.Color(51, 51, 255));
        FECHA_INICIO_SERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FECHA_INICIO_SERVICIO.setText("FECHA");

        javax.swing.GroupLayout panel25Layout = new javax.swing.GroupLayout(panel25);
        panel25.setLayout(panel25Layout);
        panel25Layout.setHorizontalGroup(
            panel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel25Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(FECHA_INICIO_SERVICIO, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        panel25Layout.setVerticalGroup(
            panel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FECHA_INICIO_SERVICIO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel3.add(panel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, 40));

        panel15.setPanel_BorderActived(true);
        panel15.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel15.setPanel_Round(0);
        panel15.setPanel_ShadowOpacity(0.0F);
        panel15.setPanel_ShadowSize(0);

        javax.swing.GroupLayout panel15Layout = new javax.swing.GroupLayout(panel15);
        panel15.setLayout(panel15Layout);
        panel15Layout.setHorizontalGroup(
            panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panel15Layout.setVerticalGroup(
            panel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel3.add(panel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, -1));

        panel20.setPanel_BorderActived(true);
        panel20.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel20.setPanel_Round(0);
        panel20.setPanel_ShadowOpacity(0.0F);
        panel20.setPanel_ShadowSize(0);

        javax.swing.GroupLayout panel20Layout = new javax.swing.GroupLayout(panel20);
        panel20.setLayout(panel20Layout);
        panel20Layout.setHorizontalGroup(
            panel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        panel20Layout.setVerticalGroup(
            panel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel3.add(panel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 80, 250, -1));

        panel21.setPanel_BorderActived(true);
        panel21.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel21.setPanel_Round(0);
        panel21.setPanel_ShadowOpacity(0.0F);
        panel21.setPanel_ShadowSize(0);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Firma y sello");
        jLabel6.setToolTipText("");

        javax.swing.GroupLayout panel21Layout = new javax.swing.GroupLayout(panel21);
        panel21.setLayout(panel21Layout);
        panel21Layout.setHorizontalGroup(
            panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel21Layout.setVerticalGroup(
            panel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel21Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(panel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 250, -1));

        panel29.setPanel_BorderActived(true);
        panel29.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel29.setPanel_Round(0);
        panel29.setPanel_ShadowOpacity(0.0F);
        panel29.setPanel_ShadowSize(0);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Firma y sello");
        jLabel12.setToolTipText("");

        javax.swing.GroupLayout panel29Layout = new javax.swing.GroupLayout(panel29);
        panel29.setLayout(panel29Layout);
        panel29Layout.setHorizontalGroup(
            panel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel29Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel29Layout.setVerticalGroup(
            panel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel29Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.add(panel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 250, -1));

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TABLA_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "N°", "ELEMENTO", "DESCRIPCION DE LA ACTIVIDAD", "CANTIDAD", "U. MEDIDA", "ESTADO FINAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLA_1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLA_1.setHeader_BackgroundColor(new java.awt.Color(204, 255, 255));
        TABLA_1.setHeader_Border(javax.swing.BorderFactory.createEmptyBorder(7, 1, 7, 1));
        TABLA_1.setHeader_Font(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLA_1.setRowHeight(28);
        TABLA_1.setRow_SelectedColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(TABLA_1);
        if (TABLA_1.getColumnModel().getColumnCount() > 0) {
            TABLA_1.getColumnModel().getColumn(0).setResizable(false);
            TABLA_1.getColumnModel().getColumn(0).setPreferredWidth(50);
            TABLA_1.getColumnModel().getColumn(1).setResizable(false);
            TABLA_1.getColumnModel().getColumn(1).setPreferredWidth(140);
            TABLA_1.getColumnModel().getColumn(2).setResizable(false);
            TABLA_1.getColumnModel().getColumn(2).setPreferredWidth(640);
            TABLA_1.getColumnModel().getColumn(3).setResizable(false);
            TABLA_1.getColumnModel().getColumn(3).setPreferredWidth(100);
            TABLA_1.getColumnModel().getColumn(4).setResizable(false);
            TABLA_1.getColumnModel().getColumn(4).setPreferredWidth(150);
            TABLA_1.getColumnModel().getColumn(5).setResizable(false);
            TABLA_1.getColumnModel().getColumn(5).setPreferredWidth(130);
        }

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 230));

        panel30.setPanel_BorderActived(true);
        panel30.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel30.setPanel_Round(0);
        panel30.setPanel_ShadowOpacity(0.0F);
        panel30.setPanel_ShadowSize(0);

        jLabel49.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel49.setText("TIEMPO DE INTERRUCCION DEL SERVICIO: ");

        jLabel50.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel50.setText("TOTAL HH PROGRAMADAS: ");

        jLabel51.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel51.setText("FECHA PROGRAMADA: ");

        jLabel74.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel74.setText("GARANTIA DEL TRABAJO (MESES):");

        jLabel75.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel75.setText("FECHA DE INICIO: ");

        jLabel76.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel76.setText("FECHA DE TERMINO: ");

        jLabel77.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel77.setText("HORA: ");

        jLabel78.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel78.setText("HORA: ");

        jLabel52.setBackground(new java.awt.Color(255, 0, 0));
        jLabel52.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(51, 51, 255));
        jLabel52.setText("Fecha servicio");

        jLabel53.setBackground(new java.awt.Color(255, 0, 0));
        jLabel53.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(51, 51, 255));
        jLabel53.setText("Fecha servicio");

        jLabel54.setBackground(new java.awt.Color(255, 0, 0));
        jLabel54.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(51, 51, 255));
        jLabel54.setText("Hora servicio");

        jLabel57.setBackground(new java.awt.Color(255, 0, 0));
        jLabel57.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(51, 51, 255));
        jLabel57.setText("Hora servicio");

        javax.swing.GroupLayout panel30Layout = new javax.swing.GroupLayout(panel30);
        panel30.setLayout(panel30Layout);
        panel30Layout.setHorizontalGroup(
            panel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel30Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel30Layout.createSequentialGroup()
                        .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)
                        .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addGroup(panel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel30Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel75, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel30Layout.createSequentialGroup()
                        .addComponent(jLabel49)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130)
                        .addComponent(jLabel76, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel30Layout.setVerticalGroup(
            panel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel30Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(panel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel74, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel75)
                    .addComponent(jLabel78, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(panel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel76)
                    .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        TABLA_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "CODIGO SAP", "ORIGEN", "DESCRIPCION DEL MATERIAL UTILIZADO", "DEVOL.(CANT)", "U.M", "CANT", "UNITARIO", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLA_2.setHeader_BackgroundColor(new java.awt.Color(204, 255, 255));
        TABLA_2.setHeader_Border(javax.swing.BorderFactory.createEmptyBorder(7, 1, 7, 1));
        TABLA_2.setHeader_Font(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLA_2.setRowHeight(28);
        jScrollPane2.setViewportView(TABLA_2);
        if (TABLA_2.getColumnModel().getColumnCount() > 0) {
            TABLA_2.getColumnModel().getColumn(0).setResizable(false);
            TABLA_2.getColumnModel().getColumn(0).setPreferredWidth(5);
            TABLA_2.getColumnModel().getColumn(1).setResizable(false);
            TABLA_2.getColumnModel().getColumn(1).setPreferredWidth(50);
            TABLA_2.getColumnModel().getColumn(2).setResizable(false);
            TABLA_2.getColumnModel().getColumn(2).setPreferredWidth(50);
            TABLA_2.getColumnModel().getColumn(3).setResizable(false);
            TABLA_2.getColumnModel().getColumn(3).setPreferredWidth(500);
            TABLA_2.getColumnModel().getColumn(4).setResizable(false);
            TABLA_2.getColumnModel().getColumn(4).setPreferredWidth(50);
            TABLA_2.getColumnModel().getColumn(5).setResizable(false);
            TABLA_2.getColumnModel().getColumn(5).setPreferredWidth(50);
            TABLA_2.getColumnModel().getColumn(6).setResizable(false);
            TABLA_2.getColumnModel().getColumn(6).setPreferredWidth(30);
            TABLA_2.getColumnModel().getColumn(7).setResizable(false);
            TABLA_2.getColumnModel().getColumn(7).setPreferredWidth(30);
            TABLA_2.getColumnModel().getColumn(8).setResizable(false);
            TABLA_2.getColumnModel().getColumn(8).setPreferredWidth(30);
        }

        panel31.setPanel_BorderActived(true);
        panel31.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel31.setPanel_Round(0);
        panel31.setPanel_ShadowOpacity(0.0F);
        panel31.setPanel_ShadowSize(0);

        jLabel95.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel95.setText("TOTAL MATERIALES (S/.): ");

        jLabel97.setBackground(new java.awt.Color(255, 0, 0));
        jLabel97.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel97.setForeground(new java.awt.Color(255, 0, 255));
        jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel97.setText("000.00");

        javax.swing.GroupLayout panel31Layout = new javax.swing.GroupLayout(panel31);
        panel31.setLayout(panel31Layout);
        panel31Layout.setHorizontalGroup(
            panel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel31Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel31Layout.setVerticalGroup(
            panel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel95, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel97, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        TABLA_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "N°", "CODIGO PERSONAL", "ESPECIALIDAD", "NOMBRES DEL PERSONAL", "HORAS EJECUTADAS", "HH", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TABLA_3.setHeader_BackgroundColor(new java.awt.Color(204, 255, 255));
        TABLA_3.setHeader_Border(javax.swing.BorderFactory.createEmptyBorder(7, 1, 7, 1));
        TABLA_3.setHeader_Font(new java.awt.Font("Arial", 1, 12)); // NOI18N
        TABLA_3.setRowHeight(25);
        TABLA_3.setRow_SelectedColor(new java.awt.Color(255, 255, 255));
        jScrollPane3.setViewportView(TABLA_3);
        if (TABLA_3.getColumnModel().getColumnCount() > 0) {
            TABLA_3.getColumnModel().getColumn(0).setResizable(false);
            TABLA_3.getColumnModel().getColumn(0).setPreferredWidth(10);
            TABLA_3.getColumnModel().getColumn(1).setResizable(false);
            TABLA_3.getColumnModel().getColumn(1).setPreferredWidth(80);
            TABLA_3.getColumnModel().getColumn(2).setResizable(false);
            TABLA_3.getColumnModel().getColumn(2).setPreferredWidth(150);
            TABLA_3.getColumnModel().getColumn(3).setResizable(false);
            TABLA_3.getColumnModel().getColumn(3).setPreferredWidth(500);
            TABLA_3.getColumnModel().getColumn(4).setResizable(false);
            TABLA_3.getColumnModel().getColumn(5).setResizable(false);
            TABLA_3.getColumnModel().getColumn(6).setResizable(false);
        }

        panel32.setPanel_BorderActived(true);
        panel32.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel32.setPanel_Round(0);
        panel32.setPanel_ShadowOpacity(0.0F);
        panel32.setPanel_ShadowSize(0);

        jLabel96.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel96.setText("TOTAL MATERIALES (S/.): ");

        jLabel98.setBackground(new java.awt.Color(255, 0, 0));
        jLabel98.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel98.setForeground(new java.awt.Color(255, 0, 255));
        jLabel98.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel98.setText("000.00");

        javax.swing.GroupLayout panel32Layout = new javax.swing.GroupLayout(panel32);
        panel32.setLayout(panel32Layout);
        panel32Layout.setHorizontalGroup(
            panel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel32Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel32Layout.setVerticalGroup(
            panel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel96, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel98, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel33.setPanel_BorderActived(true);
        panel33.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel33.setPanel_Round(0);
        panel33.setPanel_ShadowOpacity(0.0F);
        panel33.setPanel_ShadowSize(0);

        jLabel100.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel100.setText("OBSERVACIONES");

        javax.swing.GroupLayout panel33Layout = new javax.swing.GroupLayout(panel33);
        panel33.setLayout(panel33Layout);
        panel33Layout.setHorizontalGroup(
            panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel33Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel33Layout.setVerticalGroup(
            panel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel33Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel100, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel34.setPanel_BorderActived(true);
        panel34.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel34.setPanel_Round(0);
        panel34.setPanel_ShadowOpacity(0.0F);
        panel34.setPanel_ShadowSize(0);

        jLabel106.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel106.setText("MANO DE OBRA(S/.): ");

        jLabel107.setBackground(new java.awt.Color(255, 0, 0));
        jLabel107.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 0, 255));
        jLabel107.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel107.setText("000.00");

        jLabel108.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel108.setText("MATERIALES(S.):");

        jLabel109.setBackground(new java.awt.Color(255, 0, 0));
        jLabel109.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel109.setForeground(new java.awt.Color(255, 0, 255));
        jLabel109.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel109.setText("000.00");

        jLabel104.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel104.setText("CONSTOT TOTAL OTM(S/.): ");

        jLabel105.setBackground(new java.awt.Color(255, 0, 0));
        jLabel105.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel105.setForeground(new java.awt.Color(255, 0, 255));
        jLabel105.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel105.setText("000.00");

        javax.swing.GroupLayout panel34Layout = new javax.swing.GroupLayout(panel34);
        panel34.setLayout(panel34Layout);
        panel34Layout.setHorizontalGroup(
            panel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel34Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel106, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel107, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232)
                .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        panel34Layout.setVerticalGroup(
            panel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel34Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(panel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel108, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel109, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel104, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel105, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel107, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel106, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel35.setPanel_BorderActived(true);
        panel35.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel35.setPanel_Round(0);
        panel35.setPanel_ShadowOpacity(0.0F);
        panel35.setPanel_ShadowSize(0);
        panel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(130);
        jTextArea1.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        panel35.add(jTextArea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 1, -1, 39));

        panel36.setPanel_BorderActived(true);
        panel36.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel36.setPanel_Round(0);
        panel36.setPanel_ShadowOpacity(0.0F);
        panel36.setPanel_ShadowSize(0);

        javax.swing.GroupLayout panel36Layout = new javax.swing.GroupLayout(panel36);
        panel36.setLayout(panel36Layout);
        panel36Layout.setHorizontalGroup(
            panel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );
        panel36Layout.setVerticalGroup(
            panel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel37.setPanel_BorderActived(true);
        panel37.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel37.setPanel_Round(0);
        panel37.setPanel_ShadowOpacity(0.0F);
        panel37.setPanel_ShadowSize(0);

        jLabel101.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel101.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel101.setText("Firma y sello");

        javax.swing.GroupLayout panel37Layout = new javax.swing.GroupLayout(panel37);
        panel37.setLayout(panel37Layout);
        panel37Layout.setHorizontalGroup(
            panel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
            .addGroup(panel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel37Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel37Layout.setVerticalGroup(
            panel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel37Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel101, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        panel38.setPanel_BorderActived(true);
        panel38.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel38.setPanel_Round(0);
        panel38.setPanel_ShadowOpacity(0.0F);
        panel38.setPanel_ShadowSize(0);

        javax.swing.GroupLayout panel38Layout = new javax.swing.GroupLayout(panel38);
        panel38.setLayout(panel38Layout);
        panel38Layout.setHorizontalGroup(
            panel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );
        panel38Layout.setVerticalGroup(
            panel38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 91, Short.MAX_VALUE)
        );

        panel39.setPanel_BorderActived(true);
        panel39.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel39.setPanel_Round(0);
        panel39.setPanel_ShadowOpacity(0.0F);
        panel39.setPanel_ShadowSize(0);

        jLabel102.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel102.setText("Firma y sello");

        javax.swing.GroupLayout panel39Layout = new javax.swing.GroupLayout(panel39);
        panel39.setLayout(panel39Layout);
        panel39Layout.setHorizontalGroup(
            panel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
            .addGroup(panel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel39Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel39Layout.setVerticalGroup(
            panel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(panel39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel39Layout.createSequentialGroup()
                    .addGap(0, 8, Short.MAX_VALUE)
                    .addComponent(jLabel102, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 8, Short.MAX_VALUE)))
        );

        panel40.setPanel_BorderActived(true);
        panel40.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel40.setPanel_Round(0);
        panel40.setPanel_ShadowOpacity(0.0F);
        panel40.setPanel_ShadowSize(0);

        javax.swing.GroupLayout panel40Layout = new javax.swing.GroupLayout(panel40);
        panel40.setLayout(panel40Layout);
        panel40Layout.setHorizontalGroup(
            panel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
        );
        panel40Layout.setVerticalGroup(
            panel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel41.setPanel_BorderActived(true);
        panel41.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel41.setPanel_Round(0);
        panel41.setPanel_ShadowOpacity(0.0F);
        panel41.setPanel_ShadowSize(0);

        jLabel103.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel103.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel103.setText("Firma y sello");

        javax.swing.GroupLayout panel41Layout = new javax.swing.GroupLayout(panel41);
        panel41.setLayout(panel41Layout);
        panel41Layout.setHorizontalGroup(
            panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 263, Short.MAX_VALUE)
            .addGroup(panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel41Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        panel41Layout.setVerticalGroup(
            panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
            .addGroup(panel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel41Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel103, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel2.setPanel_BorderActived(true);
        panel2.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel2.setPanel_Round(0);
        panel2.setPanel_ShadowOpacity(0.0F);
        panel2.setPanel_ShadowSize(0);
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("N° OTM");
        panel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, -1, -1));

        panel3.setPanel_BorderActived(true);
        panel3.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel3.setPanel_Round(0);
        panel3.setPanel_ShadowOpacity(0.0F);
        panel3.setPanel_ShadowSize(0);
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("AÑO");
        panel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 30, -1, -1));

        panel4.setPanel_BorderActived(true);
        panel4.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel4.setPanel_Round(0);
        panel4.setPanel_ShadowOpacity(0.0F);
        panel4.setPanel_ShadowSize(0);
        panel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDSERVICIO.setBackground(new java.awt.Color(255, 0, 0));
        IDSERVICIO.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        IDSERVICIO.setForeground(new java.awt.Color(51, 51, 255));
        IDSERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDSERVICIO.setText("ID SERVICIO");
        panel4.add(IDSERVICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 30));

        jPanel1.add(panel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, -1));

        panel5.setPanel_BorderActived(true);
        panel5.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel5.setPanel_Round(0);
        panel5.setPanel_ShadowOpacity(0.0F);
        panel5.setPanel_ShadowSize(0);
        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FECHA DE EMISION");
        panel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        jPanel1.add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        panel8.setPanel_BorderActived(true);
        panel8.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel8.setPanel_Round(0);
        panel8.setPanel_ShadowOpacity(0.0F);
        panel8.setPanel_ShadowSize(0);
        panel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("MES");
        panel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.add(panel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 30, -1, -1));

        panel9.setPanel_BorderActived(true);
        panel9.setPanel_BorderColor(new java.awt.Color(0, 0, 0));
        panel9.setPanel_Round(0);
        panel9.setPanel_ShadowOpacity(0.0F);
        panel9.setPanel_ShadowSize(0);
        panel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DIA_SERVICIO.setBackground(new java.awt.Color(255, 0, 0));
        DIA_SERVICIO.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        DIA_SERVICIO.setForeground(new java.awt.Color(51, 51, 255));
        DIA_SERVICIO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DIA_SERVICIO.setText("DIA");
        panel9.add(DIA_SERVICIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 30));

        jPanel1.add(panel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 30, -1, -1));

        background_Img1.setBackground_Image(new javax.swing.ImageIcon(getClass().getResource("/img/LogoESSsalud.jpg"))); // NOI18N
        background_Img1.setBackground_ImageOpacity(0.0F);
        background_Img1.setBackground_ImgMaxMin(true);

        javax.swing.GroupLayout background_Img1Layout = new javax.swing.GroupLayout(background_Img1);
        background_Img1.setLayout(background_Img1Layout);
        background_Img1Layout.setHorizontalGroup(
            background_Img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        background_Img1Layout.setVerticalGroup(
            background_Img1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel1.add(background_Img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setText("ORDEN DE TRABAJO DE MANTENIMIENTO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel43.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel43.setText("TIPO: ");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 40, 20));

        jLabel42.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 204, 0));
        jLabel42.setText("PROGRAMADO / PREVISTO");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel37, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(203, 203, 203)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel41, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(218, 218, 218)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(panel35, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel33, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel32, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel31, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panel30, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(panel34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panel35, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(panel37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addComponent(panel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(0, 0, 0)
                        .addComponent(panel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DESCRIPCION_SERVICIO;
    private javax.swing.JLabel DIA_SERVICIO;
    private javax.swing.JLabel FECHA_FINALIZACION_SERVICIO;
    private javax.swing.JLabel FECHA_INICIO_SERVICIO;
    private javax.swing.JLabel IDSERVICIO;
    private com.mycompany.Swing.Tabla.Tabla TABLA_1;
    private com.mycompany.Swing.Tabla.Tabla TABLA_2;
    private com.mycompany.Swing.Tabla.Tabla TABLA_3;
    private javax.swing.JLabel UBICACION_SERVICIO;
    private com.mycompany.Swing.Background.Background_Img background_Img1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private com.mycompany.Swing.Panel.Panel panel10;
    private com.mycompany.Swing.Panel.Panel panel11;
    private com.mycompany.Swing.Panel.Panel panel15;
    private com.mycompany.Swing.Panel.Panel panel17;
    private com.mycompany.Swing.Panel.Panel panel2;
    private com.mycompany.Swing.Panel.Panel panel20;
    private com.mycompany.Swing.Panel.Panel panel21;
    private com.mycompany.Swing.Panel.Panel panel22;
    private com.mycompany.Swing.Panel.Panel panel24;
    private com.mycompany.Swing.Panel.Panel panel25;
    private com.mycompany.Swing.Panel.Panel panel27;
    private com.mycompany.Swing.Panel.Panel panel28;
    private com.mycompany.Swing.Panel.Panel panel29;
    private com.mycompany.Swing.Panel.Panel panel3;
    private com.mycompany.Swing.Panel.Panel panel30;
    private com.mycompany.Swing.Panel.Panel panel31;
    private com.mycompany.Swing.Panel.Panel panel32;
    private com.mycompany.Swing.Panel.Panel panel33;
    private com.mycompany.Swing.Panel.Panel panel34;
    private com.mycompany.Swing.Panel.Panel panel35;
    private com.mycompany.Swing.Panel.Panel panel36;
    private com.mycompany.Swing.Panel.Panel panel37;
    private com.mycompany.Swing.Panel.Panel panel38;
    private com.mycompany.Swing.Panel.Panel panel39;
    private com.mycompany.Swing.Panel.Panel panel4;
    private com.mycompany.Swing.Panel.Panel panel40;
    private com.mycompany.Swing.Panel.Panel panel41;
    private com.mycompany.Swing.Panel.Panel panel5;
    private com.mycompany.Swing.Panel.Panel panel6;
    private com.mycompany.Swing.Panel.Panel panel7;
    private com.mycompany.Swing.Panel.Panel panel8;
    private com.mycompany.Swing.Panel.Panel panel9;
    // End of variables declaration//GEN-END:variables

    @Override
    public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
        if (pageIndex == 0) {
            Graphics2D graphics2d = (Graphics2D) graphics;

            // Tamaño del panel
            double panelWidth = 1250;
            double panelHeight = 1680;

            // Tamaño del área imprimible
            double pageWidth = pageFormat.getImageableWidth();
            double pageHeight = pageFormat.getImageableHeight();

            // Calcular la escala
            double scaleX = pageWidth / panelWidth;
            double scaleY = pageHeight / panelHeight;
            double scale = Math.min(scaleX, scaleY);

            // Calcular desplazamiento
            double offsetX = (pageWidth - panelWidth * scale) / 2;
            double offsetY = (pageHeight - panelHeight * scale) / 2;

            // Aplicar escala y desplazamiento
            graphics2d.translate(pageFormat.getImageableX() + offsetX, pageFormat.getImageableY() + offsetY);
            graphics2d.scale(scale, scale);

            // Dibujar el panel
            this.printAll(graphics2d);

            return PAGE_EXISTS;
        } else {
            return NO_SUCH_PAGE;
        }
    }
}
